Repository databrickslabs/lakebridge, pull requests merged in 2024-04, with the labels that each got.

#222 Fixed default value for sdk config - Uninstall Errors
  src/databricks/labs/remorph/config.py
Labels: bug

#254 Added `Configure Secrets` support to `databricks labs remorph configure-secrets` cli command
  labs.yml
  src/databricks/labs/remorph/cli.py
  src/databricks/labs/remorph/helpers/recon_config_utils.py
  tests/unit/helpers/test_recon_config_utils.py
  tests/unit/test_cli.py
Labels: cli commands

#280 Support for Null safe equality join for databricks generator
  src/databricks/labs/remorph/snow/databricks.py
  tests/resources/functional/snowflake/test_nullsafe_eq/test_nullsafe_eq_1.sql
Labels: enhancement
