Repository databrickslabs/lakebridge, pull requests merged in 2024-07, with the labels that each got.

#496 Implement TSQL FOR and OPTION clauses as part of SELECT and other statements
  core/src/main/antlr4/com/databricks/labs/remorph/parsers/tsql/TSqlLexer.g4
  core/src/main/antlr4/com/databricks/labs/remorph/parsers/tsql/TSqlParser.g4
  core/src/main/scala/com/databricks/labs/remorph/parsers/GenericOption.scala
  core/src/main/scala/com/databricks/labs/remorph/parsers/intermediate/extensions.scala
  core/src/main/scala/com/databricks/labs/remorph/parsers/tsql/OptionBuilder.scala
  core/src/main/scala/com/databricks/labs/remorph/parsers/tsql/TSqlAstBuilder.scala
  core/src/main/scala/com/databricks/labs/remorph/parsers/tsql/TSqlExpressionBuilder.scala
  core/src/main/scala/com/databricks/labs/remorph/parsers/tsql/TSqlRelationBuilder.scala
  core/src/test/scala/com/databricks/labs/remorph/parsers/tsql/TSqlAstBuilderSpec.scala
Labels: internal

#499 TSQL: Implement TOP, FETCH and OFFSET clauses for TSQL SELECT
  core/src/main/antlr4/com/databricks/labs/remorph/parsers/snowflake/SnowflakeParser.g4
  core/src/main/antlr4/com/databricks/labs/remorph/parsers/tsql/TSqlParser.g4
  core/src/main/scala/com/databricks/labs/remorph/parsers/intermediate/relations.scala
  core/src/main/scala/com/databricks/labs/remorph/parsers/snowflake/SnowflakeRelationBuilder.scala
  core/src/main/scala/com/databricks/labs/remorph/parsers/tsql/TSqlRelationBuilder.scala
  core/src/test/scala/com/databricks/labs/remorph/parsers/snowflake/SnowflakeAstBuilderSpec.scala
  core/src/test/scala/com/databricks/labs/remorph/parsers/snowflake/SnowflakeRelationBuilderSpec.scala
  core/src/test/scala/com/databricks/labs/remorph/parsers/tsql/TSqlAstBuilderSpec.scala
Labels: internal

#505 TSQL: Finish all variants of expressions
  core/src/main/antlr4/com/databricks/labs/remorph/parsers/tsql/TSqlParser.g4
  core/src/main/scala/com/databricks/labs/remorph/parsers/intermediate/extensions.scala
  core/src/main/scala/com/databricks/labs/remorph/parsers/tsql/TSqlExpressionBuilder.scala
  core/src/test/scala/com/databricks/labs/remorph/parsers/tsql/TSqlAstBuilderSpec.scala
  core/src/test/scala/com/databricks/labs/remorph/parsers/tsql/TSqlExpressionBuilderSpec.scala
  core/src/test/scala/com/databricks/labs/remorph/parsers/tsql/TSqlFunctionSpec.scala
  core/src/test/scala/com/databricks/labs/remorph/parsers/tsql/TSqlRelationBuilderSpec.scala
Labels: internal

#513 TSQL: Remove more unnecessary lexer tokens, simplify grammar
  core/src/main/antlr4/com/databricks/labs/remorph/parsers/tsql/TSqlLexer.g4
  core/src/main/antlr4/com/databricks/labs/remorph/parsers/tsql/TSqlParser.g4
Labels: internal

#514 TSQL: Remove redundant tokens from TSQL lexer
  core/src/main/antlr4/com/databricks/labs/remorph/parsers/tsql/TSqlLexer.g4
  core/src/main/antlr4/com/databricks/labs/remorph/parsers/tsql/TSqlParser.g4
Labels: internal

#519 Snowflake: add support for JSON path expressions
  core/src/main/antlr4/com/databricks/labs/remorph/parsers/snowflake/SnowflakeParser.g4
  core/src/main/scala/com/databricks/labs/remorph/parsers/intermediate/extensions.scala
  core/src/main/scala/com/databricks/labs/remorph/parsers/snowflake/SnowflakeExpressionBuilder.scala
  core/src/test/scala/com/databricks/labs/remorph/parsers/snowflake/SnowflakeAstBuilderSpec.scala
  core/src/test/scala/com/databricks/labs/remorph/parsers/snowflake/SnowflakeExprSpec.scala
  core/src/test/scala/com/databricks/labs/remorph/parsers/snowflake/SnowflakeExpressionBuilderSpec.scala
  core/src/test/scala/com/databricks/labs/remorph/parsers/snowflake/SnowflakeRelationBuilderSpec.scala
Labels: internal

#521 Added propagation of Remorph version to `User-Agent` header
  pyproject.toml
  src/databricks/labs/remorph/__init__.py
  src/databricks/labs/remorph/install.py
Labels: internal

#522 patch top test case
  core/src/test/scala/com/databricks/labs/remorph/parsers/tsql/TSqlAstBuilderSpec.scala
Labels: internal

#488 Snowflake driver and user transformation to partition & join col
  src/databricks/labs/remorph/reconcile/compare.py
  src/databricks/labs/remorph/reconcile/connectors/jdbc_reader.py
  src/databricks/labs/remorph/reconcile/execute.py
  src/databricks/labs/remorph/reconcile/query_builder/hash_query.py
  src/databricks/labs/remorph/reconcile/query_builder/threshold_query.py
  tests/unit/reconcile/connectors/test_snowflake.py
  tests/unit/reconcile/query_builder/test_hash_query.py
  tests/unit/reconcile/query_builder/test_threshold_query.py
  tests/unit/reconcile/test_execute.py
Labels: internal

#536 Add support for Snowflake's date and time literals
  core/src/main/antlr4/com/databricks/labs/remorph/parsers/snowflake/SnowflakeLexer.g4
  core/src/main/antlr4/com/databricks/labs/remorph/parsers/snowflake/SnowflakeParser.g4
  core/src/main/scala/com/databricks/labs/remorph/parsers/intermediate/expressions.scala
  core/src/main/scala/com/databricks/labs/remorph/parsers/snowflake/SnowflakeExpressionBuilder.scala
  core/src/test/scala/com/databricks/labs/remorph/parsers/snowflake/SnowflakeExpressionBuilderSpec.scala
Labels: internal

#529 Implement a new error strategy for simplifying error messages
  core/src/main/scala/com/databricks/labs/remorph/parsers/ErrorCollector.scala
  core/src/main/scala/com/databricks/labs/remorph/parsers/SqlErrorStrategy.scala
  core/src/main/scala/com/databricks/labs/remorph/parsers/tsql/TSqlErrorStrategy.scala
  core/src/test/scala/com/databricks/labs/remorph/parsers/ParserTestCommon.scala
  core/src/test/scala/com/databricks/labs/remorph/parsers/tsql/TSqlAstBuilderSpec.scala
  core/src/test/scala/com/databricks/labs/remorph/parsers/tsql/TSqlErrorStategySpec.scala
  core/src/test/scala/com/databricks/labs/remorph/parsers/tsql/TSqlParserTestCommon.scala
Labels: internal

#533 Add support for Snowflake LATERAL views and table functions
  core/src/main/antlr4/com/databricks/labs/remorph/parsers/snowflake/SnowflakeParser.g4
  core/src/main/scala/com/databricks/labs/remorph/parsers/intermediate/extensions.scala
  core/src/main/scala/com/databricks/labs/remorph/parsers/intermediate/relations.scala
  core/src/main/scala/com/databricks/labs/remorph/parsers/snowflake/SnowflakeFunctionBuilder.scala
  core/src/main/scala/com/databricks/labs/remorph/parsers/snowflake/SnowflakeRelationBuilder.scala
  core/src/test/scala/com/databricks/labs/remorph/parsers/snowflake/SnowflakeRelationBuilderSpec.scala
Labels: internal

#544 Snowflake: last mile to "full coverage"
  core/src/main/antlr4/com/databricks/labs/remorph/parsers/snowflake/SnowflakeLexer.g4
  core/src/main/antlr4/com/databricks/labs/remorph/parsers/snowflake/SnowflakeParser.g4
  core/src/main/scala/com/databricks/labs/remorph/parsers/snowflake/SnowflakeExpressionBuilder.scala
  core/src/main/scala/com/databricks/labs/remorph/parsers/snowflake/SnowflakeFunctionBuilder.scala
  core/src/main/scala/com/databricks/labs/remorph/parsers/snowflake/SnowflakeRelationBuilder.scala
  core/src/test/scala/com/databricks/labs/remorph/parsers/common/FunctionBuilderSpec.scala
  core/src/test/scala/com/databricks/labs/remorph/parsers/snowflake/SnowflakeExpressionBuilderSpec.scala
  coverage/src/main/scala/com/databricks/labs/remorph/coverage/Main.scala
  coverage/src/main/scala/com/databricks/labs/remorph/coverage/QueryExtractor.scala
  coverage/src/main/scala/com/databricks/labs/remorph/coverage/QueryRunner.scala
  coverage/src/test/scala/com/databricks/labs/remorph/coverage/AcceptanceTestRunner.scala
Labels: internal

#551 Implement translation of Snowflake INSERT command
  core/src/main/antlr4/com/databricks/labs/remorph/parsers/snowflake/SnowflakeParser.g4
  core/src/main/scala/com/databricks/labs/remorph/parsers/intermediate/extensions.scala
  core/src/main/scala/com/databricks/labs/remorph/parsers/snowflake/SnowflakeAstBuilder.scala
  core/src/main/scala/com/databricks/labs/remorph/parsers/snowflake/SnowflakeDMLBuilder.scala
  core/src/main/scala/com/databricks/labs/remorph/parsers/snowflake/SnowflakeRelationBuilder.scala
  core/src/main/scala/com/databricks/labs/remorph/parsers/tsql/TSqlRelationBuilder.scala
  core/src/test/scala/com/databricks/labs/remorph/parsers/snowflake/SnowflakeAstBuilderSpec.scala
  core/src/test/scala/com/databricks/labs/remorph/parsers/snowflake/SnowflakeDMLBuilderSpec.scala
  core/src/test/scala/com/databricks/labs/remorph/parsers/tsql/TSqlAstBuilderSpec.scala
  tests/resources/functional/snowflake/test_insert/test_insert_1.sql
  tests/resources/functional/snowflake/test_insert/test_insert_2.sql
  tests/resources/functional/snowflake/test_insert/test_insert_3.sql
  tests/resources/functional/snowflake/test_insert/test_insert_overwrite_1.sql
Labels: internal

#549 remorph metrics logging for usage for experimental functions
  pyproject.toml
  src/databricks/labs/remorph/cli.py
  src/databricks/labs/remorph/transpiler/execute.py
Labels: internal

#557 [internal] fix `sqlglot-latest` query coverage environment
  pyproject.toml
Labels: internal

#553 Snowflake: implement translation of DELETE statements to IR
  core/src/main/antlr4/com/databricks/labs/remorph/parsers/snowflake/SnowflakeParser.g4
  core/src/main/scala/com/databricks/labs/remorph/parsers/intermediate/extensions.scala
  core/src/main/scala/com/databricks/labs/remorph/parsers/snowflake/SnowflakeDMLBuilder.scala
  core/src/main/scala/com/databricks/labs/remorph/parsers/snowflake/SnowflakeRelationBuilder.scala
  core/src/test/scala/com/databricks/labs/remorph/parsers/snowflake/SnowflakeAstBuilderSpec.scala
  core/src/test/scala/com/databricks/labs/remorph/parsers/snowflake/SnowflakeDMLBuilderSpec.scala
  tests/resources/functional/snowflake/test_delete/test_delete_1.sql
  tests/resources/functional/snowflake/test_delete/test_delete_2.sql
  tests/resources/functional/snowflake/test_delete/test_delete_subquery.sql
Labels: internal

#560 Snowflake implement translation of UPDATE command
  core/src/main/antlr4/com/databricks/labs/remorph/parsers/snowflake/SnowflakeParser.g4
  core/src/main/scala/com/databricks/labs/remorph/parsers/ParserCommon.scala
  core/src/main/scala/com/databricks/labs/remorph/parsers/intermediate/IRHelpers.scala
  core/src/main/scala/com/databricks/labs/remorph/parsers/intermediate/extensions.scala
  core/src/main/scala/com/databricks/labs/remorph/parsers/snowflake/SnowflakeAstBuilder.scala
  core/src/main/scala/com/databricks/labs/remorph/parsers/snowflake/SnowflakeDMLBuilder.scala
  core/src/main/scala/com/databricks/labs/remorph/parsers/snowflake/SnowflakeExpressionBuilder.scala
  core/src/main/scala/com/databricks/labs/remorph/parsers/snowflake/SnowflakeRelationBuilder.scala
  core/src/test/scala/com/databricks/labs/remorph/parsers/IRHelpers.scala
  core/src/test/scala/com/databricks/labs/remorph/parsers/common/FunctionBuilderSpec.scala
  core/src/test/scala/com/databricks/labs/remorph/parsers/snowflake/SnowflakeAstBuilderSpec.scala
  core/src/test/scala/com/databricks/labs/remorph/parsers/snowflake/SnowflakeDMLBuilderSpec.scala
  core/src/test/scala/com/databricks/labs/remorph/parsers/snowflake/SnowflakeExprSpec.scala
  core/src/test/scala/com/databricks/labs/remorph/parsers/snowflake/SnowflakeExpressionBuilderSpec.scala
  core/src/test/scala/com/databricks/labs/remorph/parsers/snowflake/SnowflakeRelationBuilderSpec.scala
  core/src/test/scala/com/databricks/labs/remorph/parsers/tsql/TSqlAstBuilderSpec.scala
  core/src/test/scala/com/databricks/labs/remorph/parsers/tsql/TSqlErrorStategySpec.scala
  core/src/test/scala/com/databricks/labs/remorph/parsers/tsql/TSqlExpressionBuilderSpec.scala
  core/src/test/scala/com/databricks/labs/remorph/parsers/tsql/TSqlFunctionSpec.scala
  core/src/test/scala/com/databricks/labs/remorph/parsers/tsql/TSqlRelationBuilderSpec.scala
  tests/resources/functional/snowflake/test_update_from_dml/test_update_from_dml_1.sql
Labels: internal

#563 Improve remorph-core coverage report, add a dry-run github workflow
  .github/workflows/push.yml
  core/src/main/scala/com/databricks/labs/remorph/parsers/ErrorCollector.scala
  coverage/src/main/scala/com/databricks/labs/remorph/coverage/Main.scala
  coverage/src/main/scala/com/databricks/labs/remorph/coverage/QueryRunner.scala
  coverage/src/main/scala/com/databricks/labs/remorph/coverage/ReportEntry.scala
Labels: internal

#477 Transpile Presto `cast as JSON` to `cast as String`
  src/databricks/labs/remorph/snow/presto.py
  tests/resources/functional/presto/test_cast_as_json/test_cast_as_json_1.sql
  tests/resources/functional/presto/test_nested_json_with_cast/test_nested_json_with_cast_1.sql
Labels: internal

#641 Fixed presto test case after sqlglot bump
  tests/resources/functional/presto/test_nested_json_with_cast/test_nested_json_with_cast_1.sql
Labels: feat/cli, internal

#704 [internal] Port subset of Apache Spark's Catalyst into remorph-core IR
  .gitignore
  core/src/main/antlr4/com/databricks/labs/remorph/parsers/tsql/TSqlParser.g4
  core/src/main/scala/com/databricks/labs/remorph/parsers/intermediate/IRHelpers.scala
  core/src/main/scala/com/databricks/labs/remorph/parsers/intermediate/Plan.scala
  core/src/main/scala/com/databricks/labs/remorph/parsers/intermediate/TreeNode.scala
  core/src/main/scala/com/databricks/labs/remorph/parsers/intermediate/catalog.scala
  core/src/main/scala/com/databricks/labs/remorph/parsers/intermediate/commands.scala
  core/src/main/scala/com/databricks/labs/remorph/parsers/intermediate/expressions.scala
  core/src/main/scala/com/databricks/labs/remorph/parsers/intermediate/extensions.scala
  core/src/main/scala/com/databricks/labs/remorph/parsers/intermediate/plans.scala
  core/src/main/scala/com/databricks/labs/remorph/parsers/intermediate/relations.scala
  core/src/main/scala/com/databricks/labs/remorph/parsers/intermediate/trees.scala
  core/src/main/scala/com/databricks/labs/remorph/parsers/intermediate/types.scala
  core/src/main/scala/com/databricks/labs/remorph/parsers/intermediate/unresolved.scala
  core/src/main/scala/com/databricks/labs/remorph/parsers/snowflake/SnowflakeAstBuilder.scala
  core/src/main/scala/com/databricks/labs/remorph/parsers/snowflake/SnowflakeExpressionBuilder.scala
  core/src/main/scala/com/databricks/labs/remorph/parsers/snowflake/SnowflakeRelationBuilder.scala
  core/src/main/scala/com/databricks/labs/remorph/parsers/tsql/TSqlAstBuilder.scala
  core/src/main/scala/com/databricks/labs/remorph/parsers/tsql/TSqlErrorStrategy.scala
  core/src/main/scala/com/databricks/labs/remorph/parsers/tsql/TSqlExpressionBuilder.scala
  core/src/main/scala/com/databricks/labs/remorph/parsers/tsql/TSqlRelationBuilder.scala
  core/src/main/scala/com/databricks/labs/remorph/utils/Strings.scala
  core/src/test/scala/com/databricks/labs/remorph/parsers/ParserTestCommon.scala
  core/src/test/scala/com/databricks/labs/remorph/parsers/common/FunctionBuilderSpec.scala
  core/src/test/scala/com/databricks/labs/remorph/parsers/snowflake/SnowLexerSpec.scala
  core/src/test/scala/com/databricks/labs/remorph/parsers/snowflake/SnowflakeAstBuilderSpec.scala
  core/src/test/scala/com/databricks/labs/remorph/parsers/snowflake/SnowflakeDDLBuilderSpec.scala
  core/src/test/scala/com/databricks/labs/remorph/parsers/snowflake/SnowflakeExprSpec.scala
  core/src/test/scala/com/databricks/labs/remorph/parsers/snowflake/SnowflakeExpressionBuilderSpec.scala
  core/src/test/scala/com/databricks/labs/remorph/parsers/snowflake/SnowflakeRelationBuilderSpec.scala
  core/src/test/scala/com/databricks/labs/remorph/parsers/tsql/TSqlAstBuilderSpec.scala
  core/src/test/scala/com/databricks/labs/remorph/parsers/tsql/TSqlExpressionBuilderSpec.scala
  core/src/test/scala/com/databricks/labs/remorph/parsers/tsql/TSqlFunctionSpec.scala
  core/src/test/scala/com/databricks/labs/remorph/parsers/tsql/TSqlLexerSpec.scala
  core/src/test/scala/com/databricks/labs/remorph/parsers/tsql/TSqlRelationBuilderSpec.scala
  coverage/src/main/scala/com/databricks/labs/remorph/coverage/QueryRunner.scala
Labels: internal

#706 [SQL Generator] Generate SQL code for literals
  core/src/main/scala/com/databricks/labs/remorph/generators/GeneratorContext.scala
  core/src/main/scala/com/databricks/labs/remorph/generators/sql/ExpressionGenerator.scala
  core/src/main/scala/com/databricks/labs/remorph/parsers/intermediate/expressions.scala
  core/src/main/scala/com/databricks/labs/remorph/parsers/intermediate/types.scala
  core/src/main/scala/com/databricks/labs/remorph/parsers/snowflake/DataTypeBuilder.scala
  core/src/test/scala/com/databricks/labs/remorph/generators/sql/ExpressionGeneratorTest.scala
  core/src/test/scala/com/databricks/labs/remorph/parsers/snowflake/DataTypeBuilderSpec.scala
Labels: internal

#714 Modified dataclass for table threshold and added documentation
  README.md
  docs/recon_configurations/README.md
  docs/recon_configurations/reconcile_config_samples.md
  src/databricks/labs/remorph/reconcile/recon_capture.py
  src/databricks/labs/remorph/reconcile/recon_config.py
  tests/unit/conftest.py
  tests/unit/reconcile/test_recon_capture.py
Labels: documentation, feat/recon

#540 TSQL: Implement TSQL UPDATE/DELETE statements
  core/src/main/antlr4/com/databricks/labs/remorph/parsers/tsql/TSqlParser.g4
  core/src/main/scala/com/databricks/labs/remorph/parsers/intermediate/extensions.scala
  core/src/main/scala/com/databricks/labs/remorph/parsers/tsql/TSqlErrorStrategy.scala
  core/src/main/scala/com/databricks/labs/remorph/parsers/tsql/TSqlExpressionBuilder.scala
  core/src/main/scala/com/databricks/labs/remorph/parsers/tsql/TSqlRelationBuilder.scala
  core/src/test/scala/com/databricks/labs/remorph/parsers/tsql/TSqlAstBuilderSpec.scala
Labels: sql/tsql, ir/dml

#718 Add TSQL coverage tests
  .github/workflows/push.yml
  Makefile
Labels: internal

#722 Generate date and timestamp literals as separate methods
  core/src/main/scala/com/databricks/labs/remorph/generators/sql/ExpressionGenerator.scala
Labels: internal

#725 [chore] cleanup IR nodes
  core/src/main/scala/com/databricks/labs/remorph/parsers/FunctionBuilder.scala
  core/src/main/scala/com/databricks/labs/remorph/parsers/intermediate/catalog.scala
  core/src/main/scala/com/databricks/labs/remorph/parsers/intermediate/ddl.scala
  core/src/main/scala/com/databricks/labs/remorph/parsers/intermediate/dml.scala
  core/src/main/scala/com/databricks/labs/remorph/parsers/intermediate/expressions.scala
  core/src/main/scala/com/databricks/labs/remorph/parsers/intermediate/extensions.scala
  core/src/main/scala/com/databricks/labs/remorph/parsers/intermediate/functions.scala
  core/src/main/scala/com/databricks/labs/remorph/parsers/intermediate/literals.scala
  core/src/main/scala/com/databricks/labs/remorph/parsers/intermediate/operators.scala
  core/src/main/scala/com/databricks/labs/remorph/parsers/intermediate/types.scala
  core/src/main/scala/com/databricks/labs/remorph/parsers/intermediate/unresolved.scala
  core/src/main/scala/com/databricks/labs/remorph/parsers/snowflake/SnowflakeExpressionBuilder.scala
  core/src/main/scala/com/databricks/labs/remorph/parsers/snowflake/expressions.scala
  core/src/main/scala/com/databricks/labs/remorph/parsers/tsql/TSqlAstBuilder.scala
  core/src/main/scala/com/databricks/labs/remorph/parsers/tsql/TSqlExpressionBuilder.scala
  core/src/main/scala/com/databricks/labs/remorph/parsers/tsql/TSqlRelationBuilder.scala
  core/src/main/scala/com/databricks/labs/remorph/parsers/tsql/expressions.scala
  core/src/main/scala/com/databricks/labs/remorph/parsers/tsql/relations.scala
  core/src/test/scala/com/databricks/labs/remorph/parsers/common/FunctionBuilderSpec.scala
  core/src/test/scala/com/databricks/labs/remorph/parsers/snowflake/SnowflakeExprSpec.scala
  core/src/test/scala/com/databricks/labs/remorph/parsers/snowflake/SnowflakeRelationBuilderSpec.scala
  core/src/test/scala/com/databricks/labs/remorph/parsers/tsql/TSqlAstBuilderSpec.scala
  core/src/test/scala/com/databricks/labs/remorph/parsers/tsql/TSqlExpressionBuilderSpec.scala
  core/src/test/scala/com/databricks/labs/remorph/parsers/tsql/TSqlRelationBuilderSpec.scala
Labels: internal

#728 [chore] move some of snowflake queries to their logical places
  tests/resources/functional/snowflake/arrays/test_array_append_1.sql
  tests/resources/functional/snowflake/arrays/test_array_cat_1.sql
  tests/resources/functional/snowflake/arrays/test_array_cat_2.sql
  tests/resources/functional/snowflake/arrays/test_array_compact_1.sql
  tests/resources/functional/snowflake/arrays/test_array_construct_compact_1.sql
  tests/resources/functional/snowflake/arrays/test_array_construct_compact_2.sql
  tests/resources/functional/snowflake/arrays/test_array_contains_1.sql
  tests/resources/functional/snowflake/arrays/test_array_distinct_1.sql
  tests/resources/functional/snowflake/arrays/test_array_except_1.sql
  tests/resources/functional/snowflake/arrays/test_array_intersection_1.sql
  tests/resources/functional/snowflake/arrays/test_array_intersection_2.sql
  tests/resources/functional/snowflake/arrays/test_array_position_1.sql
  tests/resources/functional/snowflake/arrays/test_array_prepend_1.sql
  tests/resources/functional/snowflake/arrays/test_array_remove_1.sql
  tests/resources/functional/snowflake/arrays/test_array_size_1.sql
  tests/resources/functional/snowflake/arrays/test_array_slice_1.sql
  tests/resources/functional/snowflake/arrays/test_array_slice_2.sql
  tests/resources/functional/snowflake/arrays/test_array_to_string_1.sql
  tests/resources/functional/snowflake/arrays/test_arrayagg_1.sql
  tests/resources/functional/snowflake/arrays/test_arrayagg_2.sql
  tests/resources/functional/snowflake/arrays/test_arrayagg_3.sql
  tests/resources/functional/snowflake/arrays/test_arrayagg_4.sql
  tests/resources/functional/snowflake/arrays/test_arrayagg_5.sql
  tests/resources/functional/snowflake/arrays/test_arrayagg_6.sql
  tests/resources/functional/snowflake/arrays/test_arrayagg_7.sql
  tests/resources/functional/snowflake/arrays/test_arrays_overlap_1.sql
  tests/resources/functional/snowflake/dates/test_current_date_1.sql
  tests/resources/functional/snowflake/dates/test_current_timestamp_1.sql
  tests/resources/functional/snowflake/dates/test_date_from_parts_1.sql
  tests/resources/functional/snowflake/dates/test_date_from_parts_2.sql
  tests/resources/functional/snowflake/dates/test_date_from_parts_3.sql
  tests/resources/functional/snowflake/dates/test_date_part_1.sql
  tests/resources/functional/snowflake/dates/test_date_trunc_1.sql
  tests/resources/functional/snowflake/dates/test_date_trunc_2.sql
  tests/resources/functional/snowflake/dates/test_date_trunc_3.sql
  tests/resources/functional/snowflake/dates/test_date_trunc_4.sql
  tests/resources/functional/snowflake/dates/test_dateadd_1.sql
  tests/resources/functional/snowflake/dates/test_datediff_1.sql
  tests/resources/functional/snowflake/dates/test_datediff_10.sql
  tests/resources/functional/snowflake/dates/test_datediff_11.sql
  tests/resources/functional/snowflake/dates/test_datediff_2.sql
  tests/resources/functional/snowflake/dates/test_datediff_3.sql
  tests/resources/functional/snowflake/dates/test_datediff_4.sql
  tests/resources/functional/snowflake/dates/test_datediff_5.sql
  tests/resources/functional/snowflake/dates/test_datediff_6.sql
  tests/resources/functional/snowflake/dates/test_datediff_7.sql
  tests/resources/functional/snowflake/dates/test_datediff_8.sql
  tests/resources/functional/snowflake/dates/test_datediff_9.sql
  tests/resources/functional/snowflake/dates/test_dayname_1.sql
  tests/resources/functional/snowflake/dates/test_dayname_2.sql
  tests/resources/functional/snowflake/dates/test_dayname_3.sql
Labels: internal

#729 [chore] move some of snowflake queries to their logical places
  tests/resources/functional/snowflake/aggregates/test_booland_agg_1.sql
  tests/resources/functional/snowflake/aggregates/test_booland_agg_2.sql
  tests/resources/functional/snowflake/aggregates/test_count_1.sql
  tests/resources/functional/snowflake/aggregates/test_count_if_1.sql
  tests/resources/functional/snowflake/aggregates/test_dense_rank_1.sql
  tests/resources/functional/snowflake/aggregates/test_first_value_1.sql
  tests/resources/functional/snowflake/aggregates/test_greatest_1.sql
  tests/resources/functional/snowflake/arrays/test_concat_ws_1.sql
  tests/resources/functional/snowflake/arrays/test_extract_1.sql
  tests/resources/functional/snowflake/arrays/test_flatten_1.sql
  tests/resources/functional/snowflake/arrays/test_get_1.sql
  tests/resources/functional/snowflake/dates/test_add_months_1.sql
  tests/resources/functional/snowflake/dates/test_convert_timezone_1.sql
  tests/resources/functional/snowflake/dates/test_convert_timezone_2.sql
  tests/resources/functional/snowflake/dates/test_convert_timezone_3.sql
  tests/resources/functional/snowflake/dates/test_convert_timezone_4.sql
  tests/resources/functional/snowflake/dates/test_convert_timezone_5.sql
  tests/resources/functional/snowflake/ddl/test_create_ddl_1.sql
  tests/resources/functional/snowflake/ddl/test_current_database_1.sql
  tests/resources/functional/snowflake/dml/test_delete_1.sql
  tests/resources/functional/snowflake/dml/test_delete_2.sql
  tests/resources/functional/snowflake/dml/test_delete_from_keyword_1.sql
  tests/resources/functional/snowflake/dml/test_delete_from_keyword_2.sql
  tests/resources/functional/snowflake/dml/test_delete_subquery.sql
  tests/resources/functional/snowflake/math/test_abs_1.sql
  tests/resources/functional/snowflake/math/test_asin_1.sql
  tests/resources/functional/snowflake/math/test_atan2_1.sql
  tests/resources/functional/snowflake/math/test_ceil_1.sql
  tests/resources/functional/snowflake/math/test_cos_1.sql
  tests/resources/functional/snowflake/math/test_div0_1.sql
  tests/resources/functional/snowflake/math/test_div0null_1.sql
  tests/resources/functional/snowflake/math/test_exp_1.sql
  tests/resources/functional/snowflake/math/test_floor_1.sql
  tests/resources/functional/snowflake/misc/test_any_value_1.sql
  tests/resources/functional/snowflake/misc/test_coalesce_1.sql
  tests/resources/functional/snowflake/misc/test_contains_1.sql
  tests/resources/functional/snowflake/misc/test_equal_null_1.sql
  tests/resources/functional/snowflake/misc/test_hash_1.sql
  tests/resources/functional/snowflake/misc/test_iff_1.sql
  tests/resources/functional/snowflake/misc/test_ifnull_1.sql
  tests/resources/functional/snowflake/misc/test_ifnull_2.sql
  tests/resources/functional/snowflake/operators/test_bitor_agg_1.sql
  tests/resources/functional/snowflake/operators/test_bitor_agg_2.sql
  tests/resources/functional/snowflake/stats/test_approx_percentile_1.sql
  tests/resources/functional/snowflake/stats/test_approx_top_k_1.sql
  tests/resources/functional/snowflake/stats/test_avg_1.sql
  tests/resources/functional/snowflake/stats/test_corr_1.sql
  tests/resources/functional/snowflake/stats/test_cume_dist_1.sql
  tests/resources/functional/snowflake/strings/test_base64_decode_1.sql
  tests/resources/functional/snowflake/strings/test_base64_encode_1.sql
  tests/resources/functional/snowflake/strings/test_charindex_1.sql
  tests/resources/functional/snowflake/strings/test_collate_1.sql
  tests/resources/functional/snowflake/strings/test_collate_2.sql
  tests/resources/functional/snowflake/strings/test_decode_1.sql
  tests/resources/functional/snowflake/strings/test_editdistance.sql
  tests/resources/functional/snowflake/strings/test_endswith_1.sql
Labels: internal

#730 [chore] fix coverage tests input dir parent
  .github/workflows/push.yml
  src/databricks/labs/remorph/coverage/remorph_snow_transpilation_coverage.py
Labels: internal

#733 Fixed `SELECT TOP X PERCENT` IR translation for TSQL
  core/pom.xml
  core/src/main/scala/com/databricks/labs/remorph/generators/sql/LogicalPlanGenerator.scala
  core/src/main/scala/com/databricks/labs/remorph/parsers/intermediate/expressions.scala
  core/src/main/scala/com/databricks/labs/remorph/parsers/intermediate/extensions.scala
  core/src/main/scala/com/databricks/labs/remorph/parsers/intermediate/relations.scala
  core/src/main/scala/com/databricks/labs/remorph/parsers/intermediate/rules.scala
  core/src/main/scala/com/databricks/labs/remorph/parsers/intermediate/subqueries.scala
  core/src/main/scala/com/databricks/labs/remorph/parsers/intermediate/trees.scala
  core/src/main/scala/com/databricks/labs/remorph/parsers/tsql/TSqlExpressionBuilder.scala
  core/src/main/scala/com/databricks/labs/remorph/parsers/tsql/TSqlRelationBuilder.scala
  core/src/main/scala/com/databricks/labs/remorph/parsers/tsql/expressions.scala
  core/src/main/scala/com/databricks/labs/remorph/parsers/tsql/rules/PullLimitUpwards.scala
  core/src/main/scala/com/databricks/labs/remorph/parsers/tsql/rules/TopPercentToLimitSubquery.scala
  core/src/test/scala/com/databricks/labs/remorph/parsers/ParserTestCommon.scala
  core/src/test/scala/com/databricks/labs/remorph/parsers/PlanComparison.scala
  core/src/test/scala/com/databricks/labs/remorph/parsers/tsql/TSqlAstBuilderSpec.scala
  core/src/test/scala/com/databricks/labs/remorph/parsers/tsql/rules/PullLimitUpwardsTest.scala
  core/src/test/scala/com/databricks/labs/remorph/parsers/tsql/rules/TopPercentToLimitSubqueryTest.scala
Labels: sql/tsql

#734 Added TSql transpiler
  core/src/main/scala/com/databricks/labs/remorph/transpilers/TSqlToDatabricksTranspiler.scala
  coverage/src/main/scala/com/databricks/labs/remorph/coverage/QueryRunner.scala
  coverage/src/test/scala/com/databricks/labs/remorph/coverage/AcceptanceTestRunner.scala
Labels: sql/tsql

#743 Codegen: omit the FROM clause when the child of a Project is NoTable
  core/src/main/scala/com/databricks/labs/remorph/generators/sql/LogicalPlanGenerator.scala
  core/src/test/scala/com/databricks/labs/remorph/generators/sql/LogicalPlanGeneratorTest.scala
Labels: internal

#742 Snowflake: introduce a specific call mapper
  core/src/main/scala/com/databricks/labs/remorph/generators/sql/ExpressionGenerator.scala
  core/src/main/scala/com/databricks/labs/remorph/generators/sql/LogicalPlanGenerator.scala
  core/src/main/scala/com/databricks/labs/remorph/parsers/FunctionBuilder.scala
  core/src/main/scala/com/databricks/labs/remorph/parsers/intermediate/functions.scala
  core/src/main/scala/com/databricks/labs/remorph/parsers/intermediate/operators.scala
  core/src/main/scala/com/databricks/labs/remorph/parsers/snowflake/rules/SnowflakeCallMapper.scala
  core/src/main/scala/com/databricks/labs/remorph/transpilers/SnowflakeToDatabricksTranspiler.scala
  core/src/main/scala/com/databricks/labs/remorph/transpilers/TSqlToDatabricksTranspiler.scala
  core/src/main/scala/com/databricks/labs/remorph/transpilers/Transpiler.scala
  core/src/test/scala/com/databricks/labs/remorph/generators/sql/ExpressionGeneratorTest.scala
  core/src/test/scala/com/databricks/labs/remorph/generators/sql/LogicalPlanGeneratorTest.scala
Labels: internal

#750 Introduce a SnowflakeTranspilerTest
  core/src/main/scala/com/databricks/labs/remorph/generators/sql/ExpressionGenerator.scala
  core/src/main/scala/com/databricks/labs/remorph/generators/sql/LogicalPlanGenerator.scala
  core/src/main/scala/com/databricks/labs/remorph/parsers/snowflake/SnowflakeExpressionBuilder.scala
  core/src/main/scala/com/databricks/labs/remorph/parsers/snowflake/SnowflakeRelationBuilder.scala
  core/src/test/scala/com/databricks/labs/remorph/generators/sql/LogicalPlanGeneratorTest.scala
  core/src/test/scala/com/databricks/labs/remorph/transpilers/SnowflakeToDatabricksTranspilerTest.scala
  core/src/test/scala/com/databricks/labs/remorph/transpilers/TranspilerTestCommon.scala
Labels: internal

#719 TSQL: IR implementation of MERGE
  core/src/main/antlr4/com/databricks/labs/remorph/parsers/tsql/TSqlParser.g4
  core/src/main/scala/com/databricks/labs/remorph/generators/sql/ExpressionGenerator.scala
  core/src/main/scala/com/databricks/labs/remorph/generators/sql/LogicalPlanGenerator.scala
  core/src/main/scala/com/databricks/labs/remorph/parsers/intermediate/dml.scala
  core/src/main/scala/com/databricks/labs/remorph/parsers/intermediate/extensions.scala
  core/src/main/scala/com/databricks/labs/remorph/parsers/tsql/TSqlRelationBuilder.scala
  core/src/main/scala/com/databricks/labs/remorph/parsers/tsql/relations.scala
  core/src/main/scala/com/databricks/labs/remorph/parsers/tsql/rules/TrapInsertDefaultsAction.scala
  core/src/main/scala/com/databricks/labs/remorph/transpilers/TSqlToDatabricksTranspiler.scala
  core/src/test/scala/com/databricks/labs/remorph/generators/sql/ExpressionGeneratorTest.scala
  core/src/test/scala/com/databricks/labs/remorph/generators/sql/LogicalPlanGeneratorTest.scala
  core/src/test/scala/com/databricks/labs/remorph/parsers/tsql/TSqlAstBuilderSpec.scala
  core/src/test/scala/com/databricks/labs/remorph/parsers/tsql/rules/TrapInsertDefaultActionTest.scala
Labels: feat/ir, sql/tsql, ir/dml
