Repository databrickslabs/lakebridge, pull requests merged in 2024-11, with the labels that each got.

#1051 [chore] Improved `ApplicationContext` to generically parse `--dialect` and `--source-queries` flags
  .github/workflows/push.yml
  Makefile
  core/src/main/scala/com/databricks/labs/remorph/ApplicationContext.scala
  core/src/main/scala/com/databricks/labs/remorph/Main.scala
  core/src/main/scala/com/databricks/labs/remorph/parsers/snowflake/SnowflakeDMLBuilder.scala
  core/src/main/scala/com/databricks/labs/remorph/queries/QueryExtractor.scala
  core/src/main/scala/com/databricks/labs/remorph/support/ConnectionFactory.scala
  core/src/main/scala/com/databricks/labs/remorph/support/SupportContext.scala
  core/src/main/scala/com/databricks/labs/remorph/support/snowflake/SnowflakeConnectionFactory.scala
  core/src/main/scala/com/databricks/labs/remorph/support/snowflake/SnowflakeContext.scala
  core/src/main/scala/com/databricks/labs/remorph/support/tsql/SqlServerConnectionFactory.scala
  core/src/main/scala/com/databricks/labs/remorph/support/tsql/TSqlContext.scala
  core/src/test/scala/com/databricks/labs/remorph/queries/ExampleDebuggerTest.scala
  labs.yml
  src/databricks/labs/remorph/cli.py
Labels: internal

#1053 TO_NUMBER/TO_DECIMAL/TO_NUMERIC without precision and scale
  core/src/main/scala/com/databricks/labs/remorph/parsers/snowflake/rules/SnowflakeCallMapper.scala
  core/src/test/scala/com/databricks/labs/remorph/transpilers/SnowflakeToDatabricksTranspilerTest.scala
  src/databricks/labs/remorph/snow/databricks.py
  tests/resources/functional/snowflake/functions/conversion/test_to_number/test_to_number_9.sql
  tests/resources/functional/snowflake_expected_exceptions/test_to_number_9.sql
Labels: enhancement

#1169 [Internal] Patch Python Functional Tests Formatter
  tests/unit/conftest.py
Labels: internal

#1047 Generic stored procedure parsing
  .github/workflows/push.yml
  .gitignore
  core/pom.xml
  core/src/main/antlr4/com/databricks/labs/remorph/parsers/lib/README.md
  core/src/main/antlr4/com/databricks/labs/remorph/parsers/lib/commonlex.g4
  core/src/main/antlr4/com/databricks/labs/remorph/parsers/lib/commonparse.g4
  core/src/main/antlr4/com/databricks/labs/remorph/parsers/lib/procedure.g4
  core/src/main/antlr4/com/databricks/labs/remorph/parsers/snowflake/SnowflakeLexer.g4
  core/src/main/antlr4/com/databricks/labs/remorph/parsers/snowflake/SnowflakeParser.g4
  core/src/main/antlr4/com/databricks/labs/remorph/parsers/tsql/TSqlLexer.g4
  core/src/main/antlr4/com/databricks/labs/remorph/parsers/tsql/TSqlParser.g4
  core/src/main/scala/com/databricks/labs/remorph/parsers/snowflake/SnowflakeAstBuilder.scala
  core/src/main/scala/com/databricks/labs/remorph/parsers/snowflake/SnowflakeDDLBuilder.scala
  core/src/main/scala/com/databricks/labs/remorph/parsers/snowflake/SnowflakeDMLBuilder.scala
  core/src/main/scala/com/databricks/labs/remorph/parsers/snowflake/SnowflakeErrorStrategy.scala
  core/src/main/scala/com/databricks/labs/remorph/parsers/snowflake/SnowflakeExpressionBuilder.scala
  core/src/main/scala/com/databricks/labs/remorph/parsers/snowflake/SnowflakeRelationBuilder.scala
  core/src/main/scala/com/databricks/labs/remorph/parsers/snowflake/SnowflakeTypeBuilder.scala
  core/src/main/scala/com/databricks/labs/remorph/parsers/tsql/TSqlDMLBuilder.scala
  core/src/main/scala/com/databricks/labs/remorph/parsers/tsql/TSqlErrorStrategy.scala
  core/src/main/scala/com/databricks/labs/remorph/parsers/tsql/TSqlExpressionBuilder.scala
  core/src/main/scala/com/databricks/labs/remorph/parsers/tsql/TSqlRelationBuilder.scala
  core/src/test/scala/com/databricks/labs/remorph/discovery/AnonymizerTest.scala
  core/src/test/scala/com/databricks/labs/remorph/parsers/snowflake/SnowLexerSpec.scala
  core/src/test/scala/com/databricks/labs/remorph/parsers/snowflake/SnowflakeCommandBuilderSpec.scala
  core/src/test/scala/com/databricks/labs/remorph/parsers/snowflake/SnowflakeDDLBuilderSpec.scala
  core/src/test/scala/com/databricks/labs/remorph/parsers/snowflake/SnowflakeExpressionBuilderSpec.scala
  core/src/test/scala/com/databricks/labs/remorph/parsers/snowflake/SnowflakeTypeBuilderSpec.scala
  core/src/test/scala/com/databricks/labs/remorph/parsers/tsql/TSqlAstBuilderSpec.scala
  core/src/test/scala/com/databricks/labs/remorph/parsers/tsql/TSqlExpressionBuilderSpec.scala
  tests/resources/functional/snowflake/core_engine/test_invalid_syntax/syntax_error_2.sql
  tests/resources/functional/snowflake/core_engine/test_invalid_syntax/syntax_error_3.sql
  tests/resources/functional/tsql/core_engine/test_invalid_syntax/syntax_error_1.sql
  tests/resources/functional/tsql/core_engine/test_invalid_syntax/syntax_error_2.sql
  tests/resources/functional/tsql/core_engine/test_invalid_syntax/syntax_error_3.sql
Labels: enhancement, internal, pr/ready-to-merge, sql/snowflake, sql/tsql, antlr

#1216 Fixed `CODEOWNERS`
  CODEOWNERS
Labels: internal

#1217 Limit LSQL to releases before 0.14.0
  pyproject.toml
Labels: bug, dependencies

#1211 TSQL parser support for `(LHS) UNION RHS` queries
  core/src/main/scala/com/databricks/labs/remorph/parsers/tsql/TSqlRelationBuilder.scala
  core/src/test/scala/com/databricks/labs/remorph/parsers/tsql/TSqlRelationBuilderSpec.scala
  core/src/test/scala/com/databricks/labs/remorph/transpilers/TsqlToDatabricksTranspilerTest.scala
  tests/resources/functional/tsql/set-operations/union_all_left_grouped.sql
  tests/resources/functional/tsql/set-operations/union_left_grouped.sql
Labels: enhancement, tech debt, sql/tsql

#1218 Fix implementation of Snowflake's TO_TIME/TO_TIMESTAMP functions
  core/src/main/scala/com/databricks/labs/remorph/generators/sql/ExpressionGenerator.scala
  core/src/main/scala/com/databricks/labs/remorph/intermediate/functions.scala
  core/src/main/scala/com/databricks/labs/remorph/parsers/snowflake/rules/SnowflakeCallMapper.scala
  core/src/test/scala/com/databricks/labs/remorph/generators/sql/ExpressionGeneratorTest.scala
  tests/resources/functional/snowflake/core_engine/functions/conversion/test_to_time_1.sql
  tests/resources/functional/snowflake/core_engine/functions/conversion/test_to_time_2.sql
  tests/resources/functional/snowflake/core_engine/functions/conversion/test_try_to_date_1.sql
  tests/resources/functional/snowflake/core_engine/functions/conversion/test_try_to_date_3.sql
  tests/resources/functional/snowflake/core_engine/functions/conversion/to_timestamp_1.sql
  tests/resources/functional/snowflake/core_engine/functions/conversion/to_timestamp_variable_format.sql
  tests/resources/functional/snowflake/core_engine/functions/dates/test_date_trunc_2.sql
  tests/resources/functional/snowflake/core_engine/functions/dates/test_date_trunc_3.sql
  tests/resources/functional/snowflake/core_engine/functions/dates/test_dayname_1.sql
  tests/resources/functional/snowflake/core_engine/functions/dates/test_monthname_1.sql
  tests/resources/functional/snowflake/functions/conversion/to_timestamp_1.sql
Labels: internal, sql/snowflake

#1179 bug fix for alter table add multiple columns
  core/src/main/scala/com/databricks/labs/remorph/parsers/snowflake/SnowflakeDDLBuilder.scala
  src/databricks/labs/remorph/snow/databricks.py
  src/databricks/labs/remorph/snow/snowflake.py
  tests/resources/functional/snowflake/ddl/alter/test_alter_1.sql
  tests/resources/functional/snowflake/ddl/alter/test_alter_2.sql
  tests/resources/functional/snowflake/ddl/test_create_ddl_2.sql
Labels: bug

#1237 Add tests for partially successful parsing
  core/src/test/scala/com/databricks/labs/remorph/parsers/ParserTestCommon.scala
  core/src/test/scala/com/databricks/labs/remorph/parsers/snowflake/SnowflakeAstBuilderSpec.scala
  core/src/test/scala/com/databricks/labs/remorph/transpilers/SnowflakeToDatabricksTranspilerTest.scala
  core/src/test/scala/com/databricks/labs/remorph/transpilers/TranspilerTestCommon.scala
Labels: bug

#1243 document setup for GPG signing
  CONTRIBUTING.md
Labels: documentation, internal

#1248 Tech debt: replace empty case classes with case objects
  core/src/main/scala/com/databricks/labs/remorph/generators/py/rules/PySparkStatements.scala
  core/src/main/scala/com/databricks/labs/remorph/generators/sql/LogicalPlanGenerator.scala
  core/src/main/scala/com/databricks/labs/remorph/intermediate/extensions.scala
  core/src/main/scala/com/databricks/labs/remorph/intermediate/relations.scala
  core/src/main/scala/com/databricks/labs/remorph/parsers/snowflake/SnowflakeRelationBuilder.scala
  core/src/main/scala/com/databricks/labs/remorph/parsers/tsql/TSqlExpressionBuilder.scala
  core/src/main/scala/com/databricks/labs/remorph/parsers/tsql/TSqlRelationBuilder.scala
  core/src/test/scala/com/databricks/labs/remorph/generators/sql/LogicalPlanGeneratorTest.scala
  core/src/test/scala/com/databricks/labs/remorph/parsers/snowflake/SnowflakeRelationBuilderSpec.scala
  core/src/test/scala/com/databricks/labs/remorph/parsers/tsql/TSqlAstBuilderSpec.scala
  core/src/test/scala/com/databricks/labs/remorph/parsers/tsql/TSqlExpressionBuilderSpec.scala
  core/src/test/scala/com/databricks/labs/remorph/parsers/tsql/TSqlRelationBuilderSpec.scala
Labels: tech debt, internal

#1247 patching memory leak file
  src/databricks/labs/remorph/coverage/commons.py
Labels: internal

#1245 Simplify DealiasLCAs implementation using transform
  core/src/main/scala/com/databricks/labs/remorph/parsers/snowflake/rules/DealiasLCAs.scala
  core/src/test/scala/com/databricks/labs/remorph/transpilers/SnowflakeToDatabricksTranspilerTest.scala
Labels: internal

#1232 Enclose subqueries in parenthesis
  core/src/main/scala/com/databricks/labs/remorph/generators/sql/ExpressionGenerator.scala
  core/src/main/scala/com/databricks/labs/remorph/generators/sql/LogicalPlanGenerator.scala
  core/src/test/scala/com/databricks/labs/remorph/generators/sql/LogicalPlanGeneratorTest.scala
Labels: bug

#1249 Refactor `x.tail.foldleft(x.head)` chains as `x.reduceLeft`
  core/src/main/scala/com/databricks/labs/remorph/generators/py/StatementGenerator.scala
  core/src/main/scala/com/databricks/labs/remorph/parsers/tsql/TSqlDMLBuilder.scala
  core/src/main/scala/com/databricks/labs/remorph/parsers/tsql/TSqlRelationBuilder.scala
Labels: tech debt, internal

#1257 Drop unnecessary unit test
  core/src/test/scala/com/databricks/labs/remorph/MainTest.scala
Labels: tech debt, internal

#1238 Add support for SnowFlake `SUBSTR`
  core/src/main/scala/com/databricks/labs/remorph/parsers/FunctionBuilder.scala
  core/src/main/scala/com/databricks/labs/remorph/parsers/snowflake/SnowflakeFunctionBuilder.scala
  core/src/test/scala/com/databricks/labs/remorph/parsers/common/FunctionBuilderSpec.scala
  core/src/test/scala/com/databricks/labs/remorph/parsers/snowflake/rules/SnowflakeCallMapperSpec.scala
Labels: bug, sql/snowflake

#1258 Allow easier debugging of test failures
  core/src/main/scala/com/databricks/labs/remorph/intermediate/extensions.scala
  core/src/test/scala/com/databricks/labs/remorph/transpilers/TranspilerTestCommon.scala
Labels: internal
