Repository databrickslabs/lakebridge, pull requests merged in 2024-10, with the labels that each got.

#941 Establish rules infrastructure for complexity analysis
  core/src/main/scala/com/databricks/labs/remorph/ApplicationContext.scala
  core/src/main/scala/com/databricks/labs/remorph/Main.scala
  core/src/main/scala/com/databricks/labs/remorph/coverage/EstimationReport.scala
  core/src/main/scala/com/databricks/labs/remorph/coverage/estimation/EstimationAnalyzer.scala
  core/src/main/scala/com/databricks/labs/remorph/coverage/estimation/EstimationReporter.scala
  core/src/main/scala/com/databricks/labs/remorph/coverage/estimation/Estimator.scala
  core/src/main/scala/com/databricks/labs/remorph/coverage/estimation/RuleDefinitions.scala
  core/src/main/scala/com/databricks/labs/remorph/discovery/Anonymizer.scala
  core/src/test/scala/com/databricks/labs/remorph/discovery/AnonymizerTest.scala
  core/src/test/scala/com/databricks/labs/remorph/parsers/tsql/TSqlFunctionSpec.scala
Labels: enhancement, internal, estimate/transpile

#982 Functional Test Ignore Folder
  tests/resources/functional/snowflake/core_engine/sample.sql
  tests/unit/conftest.py
Labels: internal

#949 Table comments captured as part of Snowflake Table Definition
  core/src/main/scala/com/databricks/labs/remorph/discovery/SnowflakeTableDefinitions.scala
  core/src/test/scala/com/databricks/labs/remorph/discovery/SnowflakeTableDefinitionTest.scala
  core/src/test/scala/com/databricks/labs/remorph/integration/SnowflakeTableDefinitionTest.scala
Labels: enhancement

#910 Update catalog operations logging
  src/databricks/labs/remorph/deployment/configurator.py
  src/databricks/labs/remorph/install.py
  tests/unit/deployment/test_configurator.py
Labels: feat/recon

#936 Root Table
  core/src/main/scala/com/databricks/labs/remorph/graph/TableGraph.scala
  core/src/main/scala/com/databricks/labs/remorph/graph/lineage.scala
  core/src/test/scala/com/databricks/labs/remorph/graph/TableGraphTest.scala
  core/src/test/scala/com/databricks/labs/remorph/integration/SnowflakeTableGraphTest.scala
Labels: feat/history

#961 bug fix for to_array function
  core/src/main/scala/com/databricks/labs/remorph/parsers/snowflake/SnowflakeFunctionBuilder.scala
  core/src/test/scala/com/databricks/labs/remorph/parsers/common/FunctionBuilderSpec.scala
  src/databricks/labs/remorph/snow/databricks.py
  src/databricks/labs/remorph/snow/local_expression.py
  src/databricks/labs/remorph/snow/snowflake.py
  tests/resources/functional/snowflake/functions/conversion/to_array_2.sql
Labels: bug

#962 Updated Installation to handle install errors
  src/databricks/labs/remorph/contexts/application.py
  src/databricks/labs/remorph/deployment/installation.py
  src/databricks/labs/remorph/upgrades/v0.4.0_add_main_table_operation_name_column.py
  tests/unit/deployment/test_installation.py
Labels: bug

#966 Establish incomplete parser and aggregate functions for all Visitors
  core/src/main/scala/com/databricks/labs/remorph/parsers/IncompleteParser.scala
  core/src/main/scala/com/databricks/labs/remorph/parsers/ParserCommon.scala
  core/src/main/scala/com/databricks/labs/remorph/parsers/snowflake/SnowflakeAstBuilder.scala
  core/src/main/scala/com/databricks/labs/remorph/parsers/snowflake/SnowflakeCommandBuilder.scala
  core/src/main/scala/com/databricks/labs/remorph/parsers/snowflake/SnowflakeDDLBuilder.scala
  core/src/main/scala/com/databricks/labs/remorph/parsers/snowflake/SnowflakeDMLBuilder.scala
  core/src/main/scala/com/databricks/labs/remorph/parsers/snowflake/SnowflakeExpressionBuilder.scala
  core/src/main/scala/com/databricks/labs/remorph/parsers/snowflake/SnowflakeRelationBuilder.scala
  core/src/main/scala/com/databricks/labs/remorph/parsers/tsql/TSqlAstBuilder.scala
  core/src/main/scala/com/databricks/labs/remorph/parsers/tsql/TSqlDDLBuilder.scala
  core/src/main/scala/com/databricks/labs/remorph/parsers/tsql/TSqlDMLBuilder.scala
  core/src/main/scala/com/databricks/labs/remorph/parsers/tsql/TSqlExpressionBuilder.scala
  core/src/main/scala/com/databricks/labs/remorph/parsers/tsql/TSqlRelationBuilder.scala
  core/src/test/scala/com/databricks/labs/remorph/parsers/VisitorsSpec.scala
  core/src/test/scala/com/databricks/labs/remorph/parsers/snowflake/SnowflakeRelationBuilderSpec.scala
Labels: feat/ir, internal, pr/ready-to-merge

#964 Snowflake Merge Implementation
  core/src/main/antlr4/com/databricks/labs/remorph/parsers/snowflake/SnowflakeParser.g4
  core/src/main/scala/com/databricks/labs/remorph/parsers/snowflake/SnowflakeDMLBuilder.scala
  core/src/main/scala/com/databricks/labs/remorph/parsers/snowflake/SnowflakeExpressionBuilder.scala
  core/src/test/scala/com/databricks/labs/remorph/parsers/snowflake/SnowflakeAstBuilderSpec.scala
  core/src/test/scala/com/databricks/labs/remorph/parsers/snowflake/SnowflakeDMLBuilderSpec.scala
  core/src/test/scala/com/databricks/labs/remorph/transpilers/SnowflakeToDatabricksTranspilerTest.scala
Labels: feat/ir, pr/ready-to-merge, antlr

#967 Added _null_recon documentation in README
  docs/recon_configurations/README.md
Labels: documentation, internal

#968 Basic CTAS Implementation
  core/src/main/antlr4/com/databricks/labs/remorph/parsers/snowflake/SnowflakeParser.g4
  core/src/main/scala/com/databricks/labs/remorph/generators/sql/LogicalPlanGenerator.scala
  core/src/main/scala/com/databricks/labs/remorph/parsers/snowflake/SnowflakeDDLBuilder.scala
  core/src/test/scala/com/databricks/labs/remorph/parsers/snowflake/SnowflakeDDLBuilderSpec.scala
  tests/resources/functional/snowflake/ddl/test_ctas_complex.sql
  tests/resources/functional/snowflake/ddl/test_ctas_simple.sql
Labels: feat/ir, pr/ready-to-merge, sql/snowflake, antlr

#973 Transpile Snow ARRAY_SORT function
  core/src/main/scala/com/databricks/labs/remorph/parsers/snowflake/rules/SnowflakeCallMapper.scala
Labels: do-not-merge

#975 Implement more missing visitor functions for Snowflake and TSQL
  core/src/main/scala/com/databricks/labs/remorph/parsers/snowflake/SnowflakeDDLBuilder.scala
  core/src/main/scala/com/databricks/labs/remorph/parsers/tsql/TSqlDDLBuilder.scala
Labels: pr/ready-to-merge, sql/snowflake, sql/tsql, ir/dml, ir/ddl

#984 Snowflake: Correct parsing of Array literals
  core/src/main/antlr4/com/databricks/labs/remorph/parsers/snowflake/SnowflakeParser.g4
  core/src/main/scala/com/databricks/labs/remorph/parsers/snowflake/SnowflakeExpressionBuilder.scala
  core/src/test/scala/com/databricks/labs/remorph/generators/sql/ExpressionGeneratorTest.scala
  core/src/test/scala/com/databricks/labs/remorph/parsers/snowflake/SnowflakeExpressionBuilderSpec.scala
  tests/resources/functional/snowflake/cast/test_colon_cast.sql
Labels: feat/ir, internal, pr/ready-to-merge, sql/snowflake, antlr

#983 Implement more missing visitor functions for Snowflake and TSQL
  core/src/main/scala/com/databricks/labs/remorph/parsers/snowflake/SnowflakeCommandBuilder.scala
  core/src/main/scala/com/databricks/labs/remorph/parsers/snowflake/SnowflakeDDLBuilder.scala
  core/src/main/scala/com/databricks/labs/remorph/parsers/snowflake/SnowflakeExpressionBuilder.scala
  core/src/test/scala/com/databricks/labs/remorph/parsers/snowflake/SnowflakeDDLBuilderSpec.scala
Labels: feat/ir, internal, pr/ready-to-merge, sql/snowflake, sql/tsql

#985 SNOWFLAKE: Correctly specify search conditions in Snowflake
  core/src/main/antlr4/com/databricks/labs/remorph/parsers/snowflake/SnowflakeLexer.g4
  core/src/main/antlr4/com/databricks/labs/remorph/parsers/snowflake/SnowflakeParser.g4
  core/src/main/scala/com/databricks/labs/remorph/parsers/snowflake/SnowflakeDDLBuilder.scala
  core/src/main/scala/com/databricks/labs/remorph/parsers/snowflake/SnowflakeDMLBuilder.scala
  core/src/main/scala/com/databricks/labs/remorph/parsers/snowflake/SnowflakeExpressionBuilder.scala
  core/src/main/scala/com/databricks/labs/remorph/parsers/snowflake/SnowflakeRelationBuilder.scala
  core/src/main/scala/com/databricks/labs/remorph/parsers/tsql/TSqlExpressionBuilder.scala
  core/src/test/scala/com/databricks/labs/remorph/parsers/snowflake/SnowflakeDDLBuilderSpec.scala
  core/src/test/scala/com/databricks/labs/remorph/parsers/snowflake/SnowflakeExprSpec.scala
  core/src/test/scala/com/databricks/labs/remorph/parsers/snowflake/SnowflakeExpressionBuilderSpec.scala
Labels: bug, feat/ir, pr/ready-to-merge, sql/snowflake, ir/dml, antlr

#993 Adorn all UnresolvedXXX Ir with ruleName and token name
  core/src/main/scala/com/databricks/labs/remorph/coverage/estimation/EstimationAnalyzer.scala
  core/src/main/scala/com/databricks/labs/remorph/generators/sql/ExpressionGenerator.scala
  core/src/main/scala/com/databricks/labs/remorph/generators/sql/LogicalPlanGenerator.scala
  core/src/main/scala/com/databricks/labs/remorph/intermediate/ddl.scala
  core/src/main/scala/com/databricks/labs/remorph/intermediate/unresolved.scala
  core/src/main/scala/com/databricks/labs/remorph/parsers/FunctionBuilder.scala
  core/src/main/scala/com/databricks/labs/remorph/parsers/ParserCommon.scala
  core/src/main/scala/com/databricks/labs/remorph/parsers/PlanParser.scala
  core/src/main/scala/com/databricks/labs/remorph/parsers/VisitorCoordinator.scala
  core/src/main/scala/com/databricks/labs/remorph/parsers/snowflake/SnowflakeAstBuilder.scala
  core/src/main/scala/com/databricks/labs/remorph/parsers/snowflake/SnowflakeCommandBuilder.scala
  core/src/main/scala/com/databricks/labs/remorph/parsers/snowflake/SnowflakeDDLBuilder.scala
  core/src/main/scala/com/databricks/labs/remorph/parsers/snowflake/SnowflakeDMLBuilder.scala
  core/src/main/scala/com/databricks/labs/remorph/parsers/snowflake/SnowflakeExpressionBuilder.scala
  core/src/main/scala/com/databricks/labs/remorph/parsers/snowflake/SnowflakePlanParser.scala
  core/src/main/scala/com/databricks/labs/remorph/parsers/snowflake/SnowflakeRelationBuilder.scala
  core/src/main/scala/com/databricks/labs/remorph/parsers/snowflake/SnowflakeVisitorCoordinator.scala
  core/src/main/scala/com/databricks/labs/remorph/parsers/tsql/TSqlAstBuilder.scala
  core/src/main/scala/com/databricks/labs/remorph/parsers/tsql/TSqlDDLBuilder.scala
  core/src/main/scala/com/databricks/labs/remorph/parsers/tsql/TSqlDMLBuilder.scala
  core/src/main/scala/com/databricks/labs/remorph/parsers/tsql/TSqlExpressionBuilder.scala
  core/src/main/scala/com/databricks/labs/remorph/parsers/tsql/TSqlPlanParser.scala
  core/src/main/scala/com/databricks/labs/remorph/parsers/tsql/TSqlRelationBuilder.scala
  core/src/main/scala/com/databricks/labs/remorph/parsers/tsql/TSqlVisitorCoordinator.scala
  core/src/main/scala/com/databricks/labs/remorph/parsers/tsql/rules/TopPercentToLimitSubquery.scala
  core/src/test/scala/com/databricks/labs/remorph/parsers/VisitorsSpec.scala
  core/src/test/scala/com/databricks/labs/remorph/parsers/snowflake/SnowflakeAstBuilderSpec.scala
  core/src/test/scala/com/databricks/labs/remorph/parsers/snowflake/SnowflakeCommandBuilderSpec.scala
  core/src/test/scala/com/databricks/labs/remorph/parsers/snowflake/SnowflakeDDLBuilderSpec.scala
  core/src/test/scala/com/databricks/labs/remorph/parsers/snowflake/SnowflakeDMLBuilderSpec.scala
  core/src/test/scala/com/databricks/labs/remorph/parsers/snowflake/SnowflakeExprSpec.scala
  core/src/test/scala/com/databricks/labs/remorph/parsers/snowflake/SnowflakeExpressionBuilderSpec.scala
  core/src/test/scala/com/databricks/labs/remorph/parsers/snowflake/SnowflakeParserTestCommon.scala
  core/src/test/scala/com/databricks/labs/remorph/parsers/snowflake/SnowflakeRelationBuilderSpec.scala
  core/src/test/scala/com/databricks/labs/remorph/parsers/tsql/TSqlAstBuilderSpec.scala
  core/src/test/scala/com/databricks/labs/remorph/parsers/tsql/TSqlExpressionBuilderSpec.scala
  core/src/test/scala/com/databricks/labs/remorph/parsers/tsql/TSqlFunctionSpec.scala
  core/src/test/scala/com/databricks/labs/remorph/parsers/tsql/TSqlParserTestCommon.scala
  core/src/test/scala/com/databricks/labs/remorph/parsers/tsql/rules/TopPercentToLimitSubqueryTest.scala
Labels: enhancement, feat/ir, internal, pr/ready-to-merge, sql/snowflake, sql/tsql, ir/dml, ir/ddl

#1003 Add rule name and token name to syntax error reporting
  core/src/main/scala/com/databricks/labs/remorph/intermediate/errors.scala
  core/src/main/scala/com/databricks/labs/remorph/parsers/ErrorCollector.scala
  core/src/test/scala/com/databricks/labs/remorph/parsers/tsql/TSqlErrorHandlerSpec.scala
Labels: enhancement, internal, pr/ready-to-merge

#998 Add Variant Support
  core/src/main/scala/com/databricks/labs/remorph/generators/sql/DataTypeGenerator.scala
  core/src/main/scala/com/databricks/labs/remorph/parsers/snowflake/SnowflakeTypeBuilder.scala
  core/src/test/scala/com/databricks/labs/remorph/parsers/snowflake/SnowflakeDDLBuilderSpec.scala
  core/src/test/scala/com/databricks/labs/remorph/parsers/snowflake/SnowflakeTypeBuilderSpec.scala
  tests/resources/functional/snowflake/ddl/test_create_ddl_1.sql
Labels: feat/ir, sql/snowflake

#1006 Return `Result` out of generators, instead of throwing exceptions
  core/src/main/scala/com/databricks/labs/remorph/Result.scala
  core/src/main/scala/com/databricks/labs/remorph/coverage/QueryRunner.scala
  core/src/main/scala/com/databricks/labs/remorph/coverage/ReportEntry.scala
  core/src/main/scala/com/databricks/labs/remorph/coverage/estimation/Estimator.scala
  core/src/main/scala/com/databricks/labs/remorph/discovery/Anonymizer.scala
  core/src/main/scala/com/databricks/labs/remorph/generators/Generator.scala
  core/src/main/scala/com/databricks/labs/remorph/generators/sql/DataTypeGenerator.scala
  core/src/main/scala/com/databricks/labs/remorph/generators/sql/ExpressionGenerator.scala
  core/src/main/scala/com/databricks/labs/remorph/generators/sql/LogicalPlanGenerator.scala
  core/src/main/scala/com/databricks/labs/remorph/generators/sql/OptionGenerator.scala
  core/src/main/scala/com/databricks/labs/remorph/generators/sql/package.scala
  core/src/main/scala/com/databricks/labs/remorph/graph/TableGraph.scala
  core/src/main/scala/com/databricks/labs/remorph/intermediate/errors.scala
  core/src/main/scala/com/databricks/labs/remorph/parsers/PlanParser.scala
  core/src/main/scala/com/databricks/labs/remorph/queries/QueryExtractor.scala
  core/src/main/scala/com/databricks/labs/remorph/transpilers/Result.scala
  core/src/main/scala/com/databricks/labs/remorph/transpilers/SqlGenerator.scala
  core/src/main/scala/com/databricks/labs/remorph/transpilers/Transpiler.scala
  core/src/test/scala/com/databricks/labs/remorph/generators/sql/DataTypeGeneratorTest.scala
  core/src/test/scala/com/databricks/labs/remorph/generators/sql/GeneratorTestCommon.scala
  core/src/test/scala/com/databricks/labs/remorph/generators/sql/SQLInterpolatorSpec.scala
  core/src/test/scala/com/databricks/labs/remorph/queries/ExampleDebuggerTest.scala
  core/src/test/scala/com/databricks/labs/remorph/transpilers/TranspilerTestCommon.scala
Labels: internal

#1010 Change the structure of Result to allow for accumulating errors
  core/src/main/scala/com/databricks/labs/remorph/Result.scala
  core/src/main/scala/com/databricks/labs/remorph/coverage/QueryRunner.scala
  core/src/main/scala/com/databricks/labs/remorph/coverage/ReportEntry.scala
  core/src/main/scala/com/databricks/labs/remorph/coverage/estimation/EstimationAnalyzer.scala
  core/src/main/scala/com/databricks/labs/remorph/coverage/estimation/Estimator.scala
  core/src/main/scala/com/databricks/labs/remorph/coverage/estimation/RuleDefinitions.scala
  core/src/main/scala/com/databricks/labs/remorph/discovery/Anonymizer.scala
  core/src/main/scala/com/databricks/labs/remorph/generators/Generator.scala
  core/src/main/scala/com/databricks/labs/remorph/generators/sql/BaseSQLGenerator.scala
  core/src/main/scala/com/databricks/labs/remorph/generators/sql/DataTypeGenerator.scala
  core/src/main/scala/com/databricks/labs/remorph/generators/sql/ExpressionGenerator.scala
  core/src/main/scala/com/databricks/labs/remorph/generators/sql/LogicalPlanGenerator.scala
  core/src/main/scala/com/databricks/labs/remorph/generators/sql/package.scala
  core/src/main/scala/com/databricks/labs/remorph/graph/TableGraph.scala
  core/src/main/scala/com/databricks/labs/remorph/intermediate/errors.scala
  core/src/main/scala/com/databricks/labs/remorph/parsers/PlanParser.scala
  core/src/main/scala/com/databricks/labs/remorph/queries/QueryExtractor.scala
  core/src/main/scala/com/databricks/labs/remorph/transpilers/SqlGenerator.scala
  core/src/test/scala/com/databricks/labs/remorph/generators/sql/DataTypeGeneratorTest.scala
  core/src/test/scala/com/databricks/labs/remorph/generators/sql/GeneratorTestCommon.scala
  core/src/test/scala/com/databricks/labs/remorph/generators/sql/SQLInterpolatorSpec.scala
  core/src/test/scala/com/databricks/labs/remorph/queries/ExampleDebuggerTest.scala
  core/src/test/scala/com/databricks/labs/remorph/transpilers/TranspilerTestCommon.scala
Labels: internal

#1004 Rework error return system and use it to generate parsing error and coverage stats
  core/src/main/scala/com/databricks/labs/remorph/coverage/EstimationReport.scala
  core/src/main/scala/com/databricks/labs/remorph/coverage/estimation/EstimationAnalyzer.scala
  core/src/main/scala/com/databricks/labs/remorph/coverage/estimation/EstimationReporter.scala
  core/src/main/scala/com/databricks/labs/remorph/coverage/estimation/Estimator.scala
  core/src/main/scala/com/databricks/labs/remorph/coverage/estimation/RuleDefinitions.scala
  core/src/main/scala/com/databricks/labs/remorph/generators/Generator.scala
  core/src/main/scala/com/databricks/labs/remorph/generators/sql/BaseSQLGenerator.scala
  core/src/main/scala/com/databricks/labs/remorph/generators/sql/DataTypeGenerator.scala
  core/src/main/scala/com/databricks/labs/remorph/generators/sql/ExpressionGenerator.scala
  core/src/main/scala/com/databricks/labs/remorph/generators/sql/LogicalPlanGenerator.scala
  core/src/main/scala/com/databricks/labs/remorph/intermediate/ddl.scala
  core/src/main/scala/com/databricks/labs/remorph/intermediate/errors.scala
  core/src/main/scala/com/databricks/labs/remorph/parsers/PlanParser.scala
  core/src/test/scala/com/databricks/labs/remorph/generators/sql/SQLInterpolatorSpec.scala
  core/src/test/scala/com/databricks/labs/remorph/transpilers/TranspilerTestCommon.scala
Labels: feat/ir, internal, estimate/transpile, pr/rebase

#1012 Ensure that unparsable text is not lost in the generated output
  core/src/main/scala/com/databricks/labs/remorph/parsers/ParserCommon.scala
  core/src/main/scala/com/databricks/labs/remorph/parsers/SqlErrorStrategy.scala
Labels: enhancement, feat/ir, pr/ready-to-merge

#1014 Improve error recovery code to preserve text in AST
  core/src/main/scala/com/databricks/labs/remorph/coverage/AcceptanceTestRunner.scala
  core/src/main/scala/com/databricks/labs/remorph/coverage/QueryRunner.scala
  core/src/main/scala/com/databricks/labs/remorph/coverage/ReportEntry.scala
  core/src/main/scala/com/databricks/labs/remorph/generators/sql/BaseSQLGenerator.scala
  core/src/main/scala/com/databricks/labs/remorph/generators/sql/ExpressionGenerator.scala
  core/src/main/scala/com/databricks/labs/remorph/generators/sql/LogicalPlanGenerator.scala
  core/src/main/scala/com/databricks/labs/remorph/intermediate/plans.scala
  core/src/main/scala/com/databricks/labs/remorph/parsers/ParserCommon.scala
  core/src/main/scala/com/databricks/labs/remorph/parsers/PlanParser.scala
  core/src/main/scala/com/databricks/labs/remorph/parsers/SqlErrorStrategy.scala
  core/src/main/scala/com/databricks/labs/remorph/parsers/snowflake/SnowflakeAstBuilder.scala
  core/src/main/scala/com/databricks/labs/remorph/parsers/snowflake/SnowflakeCommandBuilder.scala
  core/src/main/scala/com/databricks/labs/remorph/parsers/snowflake/SnowflakeDDLBuilder.scala
  core/src/main/scala/com/databricks/labs/remorph/parsers/snowflake/SnowflakeDMLBuilder.scala
  core/src/main/scala/com/databricks/labs/remorph/parsers/snowflake/SnowflakeExpressionBuilder.scala
  core/src/main/scala/com/databricks/labs/remorph/parsers/snowflake/SnowflakeRelationBuilder.scala
  core/src/main/scala/com/databricks/labs/remorph/transpilers/SqlGenerator.scala
  core/src/test/scala/com/databricks/labs/remorph/coverage/AcceptanceSpec.scala
  core/src/test/scala/com/databricks/labs/remorph/discovery/AnonymizerTest.scala
  core/src/test/scala/com/databricks/labs/remorph/generators/sql/ExpressionGeneratorTest.scala
  core/src/test/scala/com/databricks/labs/remorph/parsers/snowflake/SnowflakeDDLBuilderSpec.scala
  core/src/test/scala/com/databricks/labs/remorph/transpilers/SnowflakeToDatabricksTranspilerTest.scala
  tests/resources/functional/snowflake/core_engine/test_command/test_command_1.sql
  tests/resources/functional/snowflake/core_engine/test_invalid_syntax/syntax_error_1.sql
  tests/resources/functional/snowflake/core_engine/test_skip_unsupported_operations/test_skip_unsupported_operations_1.sql
  tests/resources/functional/snowflake/core_engine/test_skip_unsupported_operations/test_skip_unsupported_operations_5.sql
  tests/resources/functional/snowflake/core_engine/test_skip_unsupported_operations/test_skip_unsupported_operations_6.sql
  tests/resources/functional/snowflake/test_command/test_command_1.sql
  tests/resources/functional/snowflake/test_skip_unsupported_operations/test_skip_unsupported_operations_1.sql
  tests/resources/functional/snowflake/test_skip_unsupported_operations/test_skip_unsupported_operations_5.sql
  tests/resources/functional/snowflake/test_skip_unsupported_operations/test_skip_unsupported_operations_6.sql
Labels: internal, pr/ready-to-merge

#1019 Adorn TSQL visitors/builders with error node checking
  core/src/main/scala/com/databricks/labs/remorph/parsers/snowflake/SnowflakeDMLBuilder.scala
  core/src/main/scala/com/databricks/labs/remorph/parsers/snowflake/SnowflakeExpressionBuilder.scala
  core/src/main/scala/com/databricks/labs/remorph/parsers/snowflake/SnowflakeRelationBuilder.scala
  core/src/main/scala/com/databricks/labs/remorph/parsers/tsql/OptionBuilder.scala
  core/src/main/scala/com/databricks/labs/remorph/parsers/tsql/TSqlAstBuilder.scala
  core/src/main/scala/com/databricks/labs/remorph/parsers/tsql/TSqlDDLBuilder.scala
  core/src/main/scala/com/databricks/labs/remorph/parsers/tsql/TSqlDMLBuilder.scala
  core/src/main/scala/com/databricks/labs/remorph/parsers/tsql/TSqlExpressionBuilder.scala
  core/src/main/scala/com/databricks/labs/remorph/parsers/tsql/TSqlRelationBuilder.scala
Labels: feat/ir, internal, pr/ready-to-merge

#1020 Implement text gatherers for additional error types
  core/src/main/scala/com/databricks/labs/remorph/generators/sql/BaseSQLGenerator.scala
  core/src/main/scala/com/databricks/labs/remorph/parsers/ParserCommon.scala
  core/src/main/scala/com/databricks/labs/remorph/parsers/SqlErrorStrategy.scala
  core/src/main/scala/com/databricks/labs/remorph/parsers/snowflake/SnowflakeAstBuilder.scala
  core/src/main/scala/com/databricks/labs/remorph/parsers/snowflake/SnowflakeCommandBuilder.scala
  core/src/main/scala/com/databricks/labs/remorph/parsers/tsql/TSqlAstBuilder.scala
  core/src/test/scala/com/databricks/labs/remorph/coverage/AcceptanceSpec.scala
  core/src/test/scala/com/databricks/labs/remorph/generators/sql/ExpressionGeneratorTest.scala
  core/src/test/scala/com/databricks/labs/remorph/transpilers/SnowflakeToDatabricksTranspilerTest.scala
  tests/resources/functional/snowflake/core_engine/test_command/test_command_1.sql
  tests/resources/functional/snowflake/core_engine/test_invalid_syntax/syntax_error_1.sql
  tests/resources/functional/snowflake/core_engine/test_invalid_syntax/syntax_error_2.sql
  tests/resources/functional/snowflake/core_engine/test_invalid_syntax/syntax_error_3.sql
  tests/resources/functional/snowflake/core_engine/test_skip_unsupported_operations/test_skip_unsupported_operations_1.sql
  tests/resources/functional/snowflake/core_engine/test_skip_unsupported_operations/test_skip_unsupported_operations_5.sql
  tests/resources/functional/snowflake/core_engine/test_skip_unsupported_operations/test_skip_unsupported_operations_6.sql
  tests/resources/functional/tsql/core_engine/test_invalid_syntax/syntax_error_1.sql
  tests/resources/functional/tsql/core_engine/test_invalid_syntax/syntax_error_2.sql
  tests/resources/functional/tsql/core_engine/test_invalid_syntax/syntax_error_3.sql
Labels: feat/ir, internal

#1022 Improve Snowflake grammar to improve syntax error recovery
  core/src/main/antlr4/com/databricks/labs/remorph/parsers/snowflake/SnowflakeParser.g4
  core/src/main/antlr4/com/databricks/labs/remorph/parsers/tsql/TSqlParser.g4
  core/src/main/scala/com/databricks/labs/remorph/parsers/snowflake/SnowflakeAstBuilder.scala
  core/src/test/scala/com/databricks/labs/remorph/discovery/AnonymizerTest.scala
  core/src/test/scala/com/databricks/labs/remorph/parsers/snowflake/SnowflakeCommandBuilderSpec.scala
  tests/resources/functional/snowflake/core_engine/test_invalid_syntax/syntax_error_1.sql
  tests/resources/functional/snowflake/core_engine/test_invalid_syntax/syntax_error_2.sql
  tests/resources/functional/snowflake/core_engine/test_invalid_syntax/syntax_error_3.sql
Labels: feat/ir, internal, pr/ready-to-merge

#1023 TSQL: prevent selectListElem from ignoring valid columns when errorNodes are accumulated
  core/src/main/scala/com/databricks/labs/remorph/generators/sql/LogicalPlanGenerator.scala
  core/src/main/scala/com/databricks/labs/remorph/parsers/tsql/TSqlExpressionBuilder.scala
  core/src/main/scala/com/databricks/labs/remorph/parsers/tsql/TSqlRelationBuilder.scala
  core/src/test/scala/com/databricks/labs/remorph/parsers/tsql/TSqlExpressionBuilderSpec.scala
  tests/resources/functional/tsql/core_engine/test_invalid_syntax/syntax_error_1.sql
Labels: enhancement, feat/ir, internal, pr/ready-to-merge, sql/tsql, ir/dml

#986 Fetch table definitions for TSQL
  core/src/main/scala/com/databricks/labs/remorph/discovery/SnowflakeTableDefinitions.scala
  core/src/main/scala/com/databricks/labs/remorph/discovery/TSqlTableDefinitions.scala
  core/src/main/scala/com/databricks/labs/remorph/discovery/queries.scala
  core/src/main/scala/com/databricks/labs/remorph/generators/sql/DataTypeGenerator.scala
  core/src/main/scala/com/databricks/labs/remorph/intermediate/ddl.scala
  core/src/test/scala/com/databricks/labs/remorph/connections/TSqlConnectionFactory.scala
  core/src/test/scala/com/databricks/labs/remorph/discovery/TSqlTableDefinitionTest.scala
  core/src/test/scala/com/databricks/labs/remorph/integration/TSqlTableDefinationTest.scala
Labels: feat/history

#999 Some window functions does not support window frame conditions
  core/src/main/scala/com/databricks/labs/remorph/parsers/snowflake/SnowflakeExpressionBuilder.scala
  core/src/test/scala/com/databricks/labs/remorph/parsers/snowflake/SnowflakeExpressionBuilderSpec.scala
  core/src/test/scala/com/databricks/labs/remorph/parsers/snowflake/SnowflakeRelationBuilderSpec.scala
  src/databricks/labs/remorph/snow/databricks.py
  src/databricks/labs/remorph/snow/snowflake.py
  tests/resources/functional/snowflake/aggregates/test_dense_rank_1.sql
  tests/resources/functional/snowflake/functions/window/lag_1.sql
  tests/resources/functional/snowflake/functions/window/lead_1.sql
  tests/resources/functional/snowflake/functions/window/rank_1.sql
  tests/resources/functional/snowflake/functions/window/row_number_1.sql
Labels: bug

#989 Table comments captured as part of Snowflake Table Definition
  core/src/main/scala/com/databricks/labs/remorph/discovery/SnowflakeTableDefinitions.scala
  core/src/test/scala/com/databricks/labs/remorph/discovery/SnowflakeTableDefinitionTest.scala
  core/src/test/scala/com/databricks/labs/remorph/integration/SnowflakeTableDefinitionTest.scala
Labels: enhancement

#1018 Introduce an abstraction for handling stateful traversal of the tree
  core/src/main/scala/com/databricks/labs/remorph/Phase.scala
  core/src/main/scala/com/databricks/labs/remorph/Result.scala
  core/src/main/scala/com/databricks/labs/remorph/coverage/QueryRunner.scala
  core/src/main/scala/com/databricks/labs/remorph/coverage/estimation/Estimator.scala
  core/src/main/scala/com/databricks/labs/remorph/discovery/Anonymizer.scala
  core/src/main/scala/com/databricks/labs/remorph/generators/Generator.scala
  core/src/main/scala/com/databricks/labs/remorph/generators/package.scala
  core/src/main/scala/com/databricks/labs/remorph/generators/py/BasePythonGenerator.scala
  core/src/main/scala/com/databricks/labs/remorph/generators/py/ExpressionGenerator.scala
  core/src/main/scala/com/databricks/labs/remorph/generators/py/LogicalPlanGenerator.scala
  core/src/main/scala/com/databricks/labs/remorph/generators/py/StatementGenerator.scala
  core/src/main/scala/com/databricks/labs/remorph/generators/py/py.scala
  core/src/main/scala/com/databricks/labs/remorph/generators/sql/BaseSQLGenerator.scala
  core/src/main/scala/com/databricks/labs/remorph/generators/sql/DataTypeGenerator.scala
  core/src/main/scala/com/databricks/labs/remorph/generators/sql/ExpressionGenerator.scala
  core/src/main/scala/com/databricks/labs/remorph/generators/sql/LogicalPlanGenerator.scala
  core/src/main/scala/com/databricks/labs/remorph/generators/sql/OptionGenerator.scala
  core/src/main/scala/com/databricks/labs/remorph/generators/sql/package.scala
  core/src/main/scala/com/databricks/labs/remorph/graph/TableGraph.scala
  core/src/main/scala/com/databricks/labs/remorph/parsers/PlanParser.scala
  core/src/main/scala/com/databricks/labs/remorph/queries/QueryExtractor.scala
  core/src/main/scala/com/databricks/labs/remorph/transpilers/PySparkGenerator.scala
  core/src/main/scala/com/databricks/labs/remorph/transpilers/SnowflakeToPySparkTranspiler.scala
  core/src/main/scala/com/databricks/labs/remorph/transpilers/Source.scala
  core/src/main/scala/com/databricks/labs/remorph/transpilers/SqlGenerator.scala
  core/src/main/scala/com/databricks/labs/remorph/transpilers/Transpiler.scala
  core/src/test/scala/com/databricks/labs/remorph/generators/GeneratorTestCommon.scala
  core/src/test/scala/com/databricks/labs/remorph/generators/TBAInterpolatorSpec.scala
  core/src/test/scala/com/databricks/labs/remorph/generators/sql/DataTypeGeneratorTest.scala
  core/src/test/scala/com/databricks/labs/remorph/queries/ExampleDebuggerTest.scala
  core/src/test/scala/com/databricks/labs/remorph/transpilers/TranspilerTestCommon.scala
Labels: internal
