Repository databrickslabs/lakebridge, pull requests merged in 2024-12, with the labels that each got.

#1261 patch upgrade script
  src/databricks/labs/remorph/upgrades/v0.4.0_add_main_table_operation_name_column.py
  src/databricks/labs/remorph/upgrades/v0.6.0_alter_metrics_datatype.py
Labels: bug, internal

#1265 Chore: remove some redundant (default) arguments on case classes in a test
  core/src/test/scala/com/databricks/labs/remorph/parsers/snowflake/SnowflakeAstBuilderSpec.scala
Labels: tech debt, internal

#1259 Update TSQL grammar so that INTERSECT precedence is handled there
  core/src/main/antlr4/com/databricks/labs/remorph/parsers/tsql/TSqlParser.g4
  core/src/main/scala/com/databricks/labs/remorph/parsers/tsql/TSqlRelationBuilder.scala
  core/src/test/scala/com/databricks/labs/remorph/parsers/tsql/TSqlRelationBuilderSpec.scala
Labels: feat/ir, tech debt, sql/tsql, antlr

#1263 Style: avoid unscoped `private` fields
  core/src/main/scala/com/databricks/labs/remorph/Main.scala
  core/src/main/scala/com/databricks/labs/remorph/coverage/CoverageTest.scala
  core/src/main/scala/com/databricks/labs/remorph/coverage/runners/EnvGetter.scala
  core/src/main/scala/com/databricks/labs/remorph/coverage/runners/SnowflakeRunner.scala
  core/src/main/scala/com/databricks/labs/remorph/coverage/runners/TSqlRunner.scala
  core/src/main/scala/com/databricks/labs/remorph/discovery/Anonymizer.scala
  core/src/main/scala/com/databricks/labs/remorph/generators/orchestration/FileSet.scala
  core/src/main/scala/com/databricks/labs/remorph/generators/orchestration/FileSetGenerator.scala
  core/src/main/scala/com/databricks/labs/remorph/generators/orchestration/rules/GenerateBundleFile.scala
  core/src/main/scala/com/databricks/labs/remorph/generators/orchestration/rules/ReformatCode.scala
  core/src/main/scala/com/databricks/labs/remorph/generators/py/RuffFormatter.scala
  core/src/main/scala/com/databricks/labs/remorph/generators/py/StatementGenerator.scala
  core/src/main/scala/com/databricks/labs/remorph/generators/py/rules/PySparkExpressions.scala
  core/src/main/scala/com/databricks/labs/remorph/generators/sql/ExpressionGenerator.scala
  core/src/main/scala/com/databricks/labs/remorph/graph/TableGraph.scala
  core/src/main/scala/com/databricks/labs/remorph/intermediate/expressions.scala
  core/src/main/scala/com/databricks/labs/remorph/intermediate/literals.scala
  core/src/main/scala/com/databricks/labs/remorph/intermediate/trees.scala
  core/src/main/scala/com/databricks/labs/remorph/parsers/ErrorCollector.scala
  core/src/main/scala/com/databricks/labs/remorph/parsers/snowflake/SnowflakeErrorStrategy.scala
  core/src/main/scala/com/databricks/labs/remorph/parsers/snowflake/SnowflakeExpressionBuilder.scala
  core/src/main/scala/com/databricks/labs/remorph/parsers/snowflake/SnowflakeFunctionBuilder.scala
  core/src/main/scala/com/databricks/labs/remorph/parsers/snowflake/SnowflakePlanParser.scala
  core/src/main/scala/com/databricks/labs/remorph/parsers/snowflake/rules/ConvertFractionalSecond.scala
  core/src/main/scala/com/databricks/labs/remorph/parsers/snowflake/rules/FlattenLateralViewToExplode.scala
  core/src/main/scala/com/databricks/labs/remorph/parsers/snowflake/rules/SnowflakeCallMapper.scala
  core/src/main/scala/com/databricks/labs/remorph/parsers/snowflake/rules/SnowflakeTimeUnits.scala
  core/src/main/scala/com/databricks/labs/remorph/parsers/tsql/TSqlErrorStrategy.scala
  core/src/main/scala/com/databricks/labs/remorph/parsers/tsql/TSqlFunctionBuilder.scala
  core/src/main/scala/com/databricks/labs/remorph/parsers/tsql/rules/TopPercentToLimitSubquery.scala
  core/src/main/scala/com/databricks/labs/remorph/queries/QueryExtractor.scala
  core/src/main/scala/com/databricks/labs/remorph/support/snowflake/SnowflakeConnectionFactory.scala
  core/src/main/scala/com/databricks/labs/remorph/support/snowflake/SnowflakeContext.scala
  core/src/main/scala/com/databricks/labs/remorph/support/tsql/SqlServerConnectionFactory.scala
  core/src/main/scala/com/databricks/labs/remorph/support/tsql/TSqlContext.scala
  core/src/main/scala/com/databricks/labs/remorph/transpilers/PySparkGenerator.scala
  core/src/main/scala/com/databricks/labs/remorph/transpilers/Source.scala
  core/src/main/scala/com/databricks/labs/remorph/transpilers/SqlGenerator.scala
  core/src/main/scala/com/databricks/labs/remorph/transpilers/Transpiler.scala
  core/src/test/scala/com/databricks/labs/remorph/connections/EnvGetter.scala
  core/src/test/scala/com/databricks/labs/remorph/connections/SnowflakeConnectionFactory.scala
  core/src/test/scala/com/databricks/labs/remorph/connections/TSqlConnectionFactory.scala
  core/src/test/scala/com/databricks/labs/remorph/generators/orchestration/FileSetGeneratorTest.scala
  core/src/test/scala/com/databricks/labs/remorph/generators/orchestration/rules/GenerateBundleFileTest.scala
  core/src/test/scala/com/databricks/labs/remorph/generators/py/ExpressionGeneratorTest.scala
  core/src/test/scala/com/databricks/labs/remorph/generators/sql/ExpressionGeneratorTest.scala
  core/src/test/scala/com/databricks/labs/remorph/graph/TableGraphTest.scala
  core/src/test/scala/com/databricks/labs/remorph/parsers/snowflake/SnowLexerSpec.scala
  core/src/test/scala/com/databricks/labs/remorph/parsers/snowflake/rules/SnowflakeCallMapperSpec.scala
  core/src/test/scala/com/databricks/labs/remorph/parsers/tsql/TSqlExpressionGeneratorTest.scala
  core/src/test/scala/com/databricks/labs/remorph/parsers/tsql/TSqlFunctionBuilderSpec.scala
  core/src/test/scala/com/databricks/labs/remorph/parsers/tsql/TSqlLexerSpec.scala
  core/src/test/scala/com/databricks/labs/remorph/parsers/tsql/rules/TSqlCallMapperSpec.scala
  core/src/test/scala/com/databricks/labs/remorph/transpilers/SnowflakeToPySparkTranspilerTest.scala
  core/src/test/scala/toolchain/ToolchainSpec.scala
  linter/src/main/scala/com/databricks/labs/remorph/linter/RuleTracker.scala
Labels: tech debt, internal

#1273 Fix precedence of CTEs with respect to set operations in SnowFlake
  core/src/main/scala/com/databricks/labs/remorph/parsers/snowflake/SnowflakeAstBuilder.scala
  core/src/test/scala/com/databricks/labs/remorph/parsers/snowflake/SnowflakeAstBuilderSpec.scala
  core/src/test/scala/com/databricks/labs/remorph/transpilers/SnowflakeToDatabricksTranspilerTest.scala
  core/src/test/scala/com/databricks/labs/remorph/transpilers/TsqlToDatabricksTranspilerTest.scala
  tests/resources/functional/snowflake/core_engine/test_cte/cte_set_operation_precedence.sql
  tests/resources/functional/snowflake/core_engine/test_cte/multiple_cte.sql
  tests/resources/functional/snowflake/cte/cte_with_column_list.sql
  tests/resources/functional/snowflake/cte/simple_cte.sql
  tests/resources/functional/tsql/cte/cte_set_operation_precedence.sql
  tests/resources/functional/tsql/cte/cte_with_column_list.sql
  tests/resources/functional/tsql/cte/multiple_cte.sql
  tests/resources/functional/tsql/cte/simple_cte.sql
Labels: bug, feat/ir, sql/snowflake

#1168 Create preprocessor and workflow for Jinja template processing
  core/src/main/antlr4/com/databricks/labs/remorph/parsers/lib/commonlex.g4
  core/src/main/antlr4/com/databricks/labs/remorph/parsers/lib/commonparse.g4
  core/src/main/antlr4/com/databricks/labs/remorph/parsers/lib/jinja.g4
  core/src/main/antlr4/com/databricks/labs/remorph/parsers/lib/procedure.g4
  core/src/main/antlr4/com/databricks/labs/remorph/parsers/preprocessor/DBTPreprocessorLexer.g4
  core/src/main/antlr4/com/databricks/labs/remorph/parsers/snowflake/SnowflakeLexer.g4
  core/src/main/antlr4/com/databricks/labs/remorph/parsers/snowflake/SnowflakeParser.g4
  core/src/main/antlr4/com/databricks/labs/remorph/parsers/tsql/TSqlLexer.g4
  core/src/main/antlr4/com/databricks/labs/remorph/parsers/tsql/TSqlParser.g4
  core/src/main/scala/com/databricks/labs/remorph/Main.scala
  core/src/main/scala/com/databricks/labs/remorph/Phase.scala
  core/src/main/scala/com/databricks/labs/remorph/Result.scala
  core/src/main/scala/com/databricks/labs/remorph/coverage/QueryRunner.scala
  core/src/main/scala/com/databricks/labs/remorph/coverage/estimation/Estimator.scala
  core/src/main/scala/com/databricks/labs/remorph/discovery/Anonymizer.scala
  core/src/main/scala/com/databricks/labs/remorph/generators/Generator.scala
  core/src/main/scala/com/databricks/labs/remorph/generators/orchestration/rules/QueryHistoryToQueryNodes.scala
  core/src/main/scala/com/databricks/labs/remorph/generators/orchestration/rules/TryGeneratePythonNotebook.scala
  core/src/main/scala/com/databricks/labs/remorph/generators/orchestration/rules/TryGenerateSQL.scala
  core/src/main/scala/com/databricks/labs/remorph/generators/sql/DataTypeGenerator.scala
  core/src/main/scala/com/databricks/labs/remorph/generators/sql/ExpressionGenerator.scala
  core/src/main/scala/com/databricks/labs/remorph/generators/sql/LogicalPlanGenerator.scala
  core/src/main/scala/com/databricks/labs/remorph/graph/TableGraph.scala
  core/src/main/scala/com/databricks/labs/remorph/intermediate/errors.scala
  core/src/main/scala/com/databricks/labs/remorph/intermediate/extensions.scala
  core/src/main/scala/com/databricks/labs/remorph/parsers/PlanParser.scala
  core/src/main/scala/com/databricks/labs/remorph/parsers/snowflake/SnowflakeErrorStrategy.scala
  core/src/main/scala/com/databricks/labs/remorph/parsers/snowflake/SnowflakeExpressionBuilder.scala
  core/src/main/scala/com/databricks/labs/remorph/parsers/snowflake/rules/CastParseJsonToFromJson.scala
  core/src/main/scala/com/databricks/labs/remorph/parsers/tsql/DataTypeBuilder.scala
  core/src/main/scala/com/databricks/labs/remorph/parsers/tsql/TSqlAstBuilder.scala
  core/src/main/scala/com/databricks/labs/remorph/parsers/tsql/TSqlErrorStrategy.scala
  core/src/main/scala/com/databricks/labs/remorph/parsers/tsql/TSqlExpressionBuilder.scala
  core/src/main/scala/com/databricks/labs/remorph/parsers/tsql/TSqlRelationBuilder.scala
  core/src/main/scala/com/databricks/labs/remorph/preprocessors/Processor.scala
  core/src/main/scala/com/databricks/labs/remorph/preprocessors/README.md
  core/src/main/scala/com/databricks/labs/remorph/preprocessors/jinja/JinjaProcessor.scala
  core/src/main/scala/com/databricks/labs/remorph/preprocessors/jinja/TemplateElement.scala
  core/src/main/scala/com/databricks/labs/remorph/preprocessors/jinja/TemplateManager.scala
  core/src/main/scala/com/databricks/labs/remorph/queries/QueryExtractor.scala
  core/src/main/scala/com/databricks/labs/remorph/transpilers/SnowflakeToPySparkTranspiler.scala
  core/src/main/scala/com/databricks/labs/remorph/transpilers/Transpiler.scala
  core/src/main/scala/com/databricks/labs/remorph/utils/Strings.scala
  core/src/test/scala/com/databricks/labs/remorph/TransformationTest.scala
  core/src/test/scala/com/databricks/labs/remorph/generators/CodeInterpolatorSpec.scala
  core/src/test/scala/com/databricks/labs/remorph/generators/GeneratorTestCommon.scala
  core/src/test/scala/com/databricks/labs/remorph/generators/orchestration/FileSetGeneratorTest.scala
  core/src/test/scala/com/databricks/labs/remorph/generators/sql/DataTypeGeneratorTest.scala
  core/src/test/scala/com/databricks/labs/remorph/parsers/snowflake/SnowLexerSpec.scala
  core/src/test/scala/com/databricks/labs/remorph/parsers/tsql/TSqlErrorStategySpec.scala
  core/src/test/scala/com/databricks/labs/remorph/parsers/tsql/TSqlLexerSpec.scala
  core/src/test/scala/com/databricks/labs/remorph/preprocessors/jinja/JinjaProcessorTest.scala
  core/src/test/scala/com/databricks/labs/remorph/queries/ExampleDebuggerTest.scala
  core/src/test/scala/com/databricks/labs/remorph/transpilers/TranspilerTestCommon.scala
  tests/resources/functional/tsql/core_engine/dbt/nofmt_twisted_input.sql
Labels: enhancement, do-not-merge, internal, orchestrator/dbt, preprocessing

#1282 Mark incorrect functional test fixture for Snowflake's `RANDOM()`
  tests/resources/functional/snowflake/functions/math/random_1.sql
Labels: bug, tech debt, internal, sql/snowflake

#1277 Fix dropped set operations within a CTE in Snowflake
  core/src/main/scala/com/databricks/labs/remorph/parsers/snowflake/SnowflakeAstBuilder.scala
  core/src/main/scala/com/databricks/labs/remorph/parsers/snowflake/SnowflakeRelationBuilder.scala
  core/src/test/scala/com/databricks/labs/remorph/parsers/snowflake/SnowflakeAstBuilderSpec.scala
  core/src/test/scala/com/databricks/labs/remorph/transpilers/SnowflakeToDatabricksTranspilerTest.scala
  tests/resources/functional/snowflake/core_engine/test_cte/nested_set_operation.sql
  tests/resources/functional/tsql/cte/nested_set_operation.sql
Labels: bug, feat/ir, sql/snowflake

#1289 Upgrade jdbc dependencies
  .github/dependabot.yml
  core/pom.xml
Labels: internal

#1300 Fix TSQL precedence of `INTERSECT` with respect to `UNION`/`EXCEPT`
  core/src/main/antlr4/com/databricks/labs/remorph/parsers/tsql/TSqlParser.g4
  core/src/test/scala/com/databricks/labs/remorph/parsers/tsql/TSqlRelationBuilderSpec.scala
  core/src/test/scala/com/databricks/labs/remorph/transpilers/TsqlToDatabricksTranspilerTest.scala
  tests/resources/functional/tsql/set-operations/precedence.sql
Labels: bug, sql/tsql, antlr

#1322 Prevent Dependabot from upgrading Databricks Connect.
  .github/dependabot.yml
  core/pom.xml
Labels: dependencies, java

#1331 Mark scala as a dependency for Dependabot to ignore.
  .github/dependabot.yml
  pom.xml
Labels: dependencies, java

#1339 Fix dependabot configuration
  .github/dependabot.yml
Labels: internal

#1342 Configure Dependabot to ignore Mockito from 5.x onwards.
  .github/dependabot.yml
Labels: internal

#1350 Fix logical plan for `LIMIT` when combined with `OFFSET`
  core/src/main/scala/com/databricks/labs/remorph/generators/sql/LogicalPlanGenerator.scala
  core/src/main/scala/com/databricks/labs/remorph/parsers/snowflake/SnowflakeRelationBuilder.scala
  core/src/test/scala/com/databricks/labs/remorph/generators/sql/LogicalPlanGeneratorTest.scala
Labels: bug, sql/snowflake, sql/tsql

#1349 TSql: fix precedence of `ORDER BY` clause
  core/src/main/antlr4/com/databricks/labs/remorph/parsers/tsql/TSqlParser.g4
  core/src/main/scala/com/databricks/labs/remorph/parsers/tsql/TSqlRelationBuilder.scala
  core/src/test/scala/com/databricks/labs/remorph/parsers/tsql/TSqlAstBuilderSpec.scala
  core/src/test/scala/com/databricks/labs/remorph/parsers/tsql/TSqlRelationBuilderSpec.scala
  core/src/test/scala/com/databricks/labs/remorph/transpilers/TsqlToDatabricksTranspilerTest.scala
  tests/resources/functional/tsql/select/limit.sql
  tests/resources/functional/tsql/select/order_by.sql
  tests/resources/functional/tsql/select/order_by_asc.sql
  tests/resources/functional/tsql/select/order_by_desc.sql
  tests/resources/functional/tsql/select/order_by_offset.sql
  tests/resources/functional/tsql/select/order_by_precedence.sql
Labels: bug, feat/ir, tech debt, sql/tsql, antlr

#1346 Make Rule[T] return a Transformation[T]
  core/src/main/scala/com/databricks/labs/remorph/Phase.scala
  core/src/main/scala/com/databricks/labs/remorph/Result.scala
  core/src/main/scala/com/databricks/labs/remorph/coverage/estimation/Estimator.scala
  core/src/main/scala/com/databricks/labs/remorph/discovery/Anonymizer.scala
  core/src/main/scala/com/databricks/labs/remorph/generators/orchestration/FileSetGenerator.scala
  core/src/main/scala/com/databricks/labs/remorph/generators/orchestration/rules/DefineJob.scala
  core/src/main/scala/com/databricks/labs/remorph/generators/orchestration/rules/DefineSchemas.scala
  core/src/main/scala/com/databricks/labs/remorph/generators/orchestration/rules/ExtractVariables.scala
  core/src/main/scala/com/databricks/labs/remorph/generators/orchestration/rules/GenerateBundleFile.scala
  core/src/main/scala/com/databricks/labs/remorph/generators/orchestration/rules/QueryHistoryToQueryNodes.scala
  core/src/main/scala/com/databricks/labs/remorph/generators/orchestration/rules/ReformatCode.scala
  core/src/main/scala/com/databricks/labs/remorph/generators/orchestration/rules/TryGeneratePythonNotebook.scala
  core/src/main/scala/com/databricks/labs/remorph/generators/orchestration/rules/TryGenerateSQL.scala
  core/src/main/scala/com/databricks/labs/remorph/generators/orchestration/rules/TrySummarizeFailures.scala
  core/src/main/scala/com/databricks/labs/remorph/generators/py/rules/AndOrToBitwise.scala
  core/src/main/scala/com/databricks/labs/remorph/generators/py/rules/DotToFCol.scala
  core/src/main/scala/com/databricks/labs/remorph/generators/py/rules/ImportClasses.scala
  core/src/main/scala/com/databricks/labs/remorph/generators/py/rules/PySparkExpressions.scala
  core/src/main/scala/com/databricks/labs/remorph/generators/py/rules/PySparkStatements.scala
  core/src/main/scala/com/databricks/labs/remorph/intermediate/errors.scala
  core/src/main/scala/com/databricks/labs/remorph/intermediate/functions.scala
  core/src/main/scala/com/databricks/labs/remorph/intermediate/plans.scala
  core/src/main/scala/com/databricks/labs/remorph/intermediate/rules.scala
  core/src/main/scala/com/databricks/labs/remorph/intermediate/trees.scala
  core/src/main/scala/com/databricks/labs/remorph/package.scala
  core/src/main/scala/com/databricks/labs/remorph/parsers/PlanParser.scala
  core/src/main/scala/com/databricks/labs/remorph/parsers/snowflake/rules/CastParseJsonToFromJson.scala
  core/src/main/scala/com/databricks/labs/remorph/parsers/snowflake/rules/CompactJsonAccess.scala
  core/src/main/scala/com/databricks/labs/remorph/parsers/snowflake/rules/ConvertFractionalSecond.scala
  core/src/main/scala/com/databricks/labs/remorph/parsers/snowflake/rules/DealiasInlineColumnExpressions.scala
  core/src/main/scala/com/databricks/labs/remorph/parsers/snowflake/rules/DealiasLCAs.scala
  core/src/main/scala/com/databricks/labs/remorph/parsers/snowflake/rules/FlattenLateralViewToExplode.scala
  core/src/main/scala/com/databricks/labs/remorph/parsers/snowflake/rules/FlattenNestedConcat.scala
  core/src/main/scala/com/databricks/labs/remorph/parsers/snowflake/rules/SnowflakeCallMapper.scala
  core/src/main/scala/com/databricks/labs/remorph/parsers/snowflake/rules/SnowflakeTimeUnits.scala
  core/src/main/scala/com/databricks/labs/remorph/parsers/snowflake/rules/TranslateWithinGroup.scala
  core/src/main/scala/com/databricks/labs/remorph/parsers/snowflake/rules/UpdateToMerge.scala
  core/src/main/scala/com/databricks/labs/remorph/parsers/tsql/rules/PullLimitUpwards.scala
  core/src/main/scala/com/databricks/labs/remorph/parsers/tsql/rules/TSqlCallMapper.scala
  core/src/main/scala/com/databricks/labs/remorph/parsers/tsql/rules/TopPercentToLimitSubquery.scala
  core/src/main/scala/com/databricks/labs/remorph/parsers/tsql/rules/TrapInsertDefaultsAction.scala
  core/src/main/scala/com/databricks/labs/remorph/transpilers/PySparkGenerator.scala
  core/src/test/scala/com/databricks/labs/remorph/discovery/AnonymizerTest.scala
  core/src/test/scala/com/databricks/labs/remorph/generators/orchestration/rules/GenerateBundleFileTest.scala
  core/src/test/scala/com/databricks/labs/remorph/parsers/ParserTestCommon.scala
  core/src/test/scala/com/databricks/labs/remorph/parsers/PlanComparison.scala
  core/src/test/scala/com/databricks/labs/remorph/parsers/snowflake/rules/DealiasLCAsSpec.scala
  core/src/test/scala/com/databricks/labs/remorph/parsers/snowflake/rules/FlattenNestedConcatSpec.scala
  core/src/test/scala/com/databricks/labs/remorph/parsers/snowflake/rules/SnowflakeCallMapperSpec.scala
  core/src/test/scala/com/databricks/labs/remorph/parsers/tsql/rules/TSqlCallMapperSpec.scala
  core/src/test/scala/com/databricks/labs/remorph/parsers/tsql/rules/TrapInsertDefaultActionTest.scala
Labels: tech debt

#1381 fix issue where unit tests would create files not ignored by git
  tests/unit/transpiler/test_execute.py
Labels: bug
