Repository databrickslabs/lakebridge, pull requests merged in 2024-06, with the labels that each got.

#409 feat: Implement coverage tests for TSQL
  coverage/src/main/scala/com/databricks/labs/remorph/coverage/Main.scala
  coverage/src/main/scala/com/databricks/labs/remorph/coverage/QueryExtractor.scala
  coverage/src/main/scala/com/databricks/labs/remorph/coverage/QueryRunner.scala
  coverage/src/test/scala/com/databricks/labs/remorph/coverage/AcceptanceTestRunner.scala
  tests/resources/functional/tsql/test_zeroifnull/test_isnull_1.sql
Labels: internal, pr/ready-to-merge

#407 Snowflake: improve acceptance coverage by avoiding NPEs
  core/src/main/antlr4/com/databricks/labs/remorph/parsers/snowflake/SnowflakeParser.g4
  core/src/main/scala/com/databricks/labs/remorph/parsers/FunctionBuilder.scala
  core/src/main/scala/com/databricks/labs/remorph/parsers/ParserCommon.scala
  core/src/main/scala/com/databricks/labs/remorph/parsers/intermediate/relations.scala
  core/src/main/scala/com/databricks/labs/remorph/parsers/snowflake/SnowflakeDDLBuilder.scala
  core/src/main/scala/com/databricks/labs/remorph/parsers/snowflake/SnowflakeExpressionBuilder.scala
  core/src/main/scala/com/databricks/labs/remorph/parsers/snowflake/SnowflakeRelationBuilder.scala
  core/src/main/scala/com/databricks/labs/remorph/parsers/tsql/TSqlExpressionBuilder.scala
  core/src/test/scala/com/databricks/labs/remorph/parsers/snowflake/SnowflakeAstBuilderSpec.scala
  core/src/test/scala/com/databricks/labs/remorph/parsers/snowflake/SnowflakeExprSpec.scala
  core/src/test/scala/com/databricks/labs/remorph/parsers/snowflake/SnowflakeExpressionBuilderSpec.scala
  core/src/test/scala/com/databricks/labs/remorph/parsers/snowflake/SnowflakeRelationBuilderSpec.scala
Labels: internal

#401 Add full support for analytical windowing functions
  core/src/main/antlr4/com/databricks/labs/remorph/parsers/tsql/TSqlLexer.g4
  core/src/main/antlr4/com/databricks/labs/remorph/parsers/tsql/TSqlParser.g4
  core/src/main/scala/com/databricks/labs/remorph/parsers/FunctionBuilder.scala
  core/src/main/scala/com/databricks/labs/remorph/parsers/intermediate/extensions.scala
  core/src/main/scala/com/databricks/labs/remorph/parsers/tsql/TSqlExpressionBuilder.scala
  core/src/test/scala/com/databricks/labs/remorph/parsers/common/FunctionBuilderSpec.scala
  core/src/test/scala/com/databricks/labs/remorph/parsers/tsql/TSqlFunctionSpec.scala
Labels: pr/ready-to-merge

#429 Intermediate cache to volumes
  src/databricks/labs/remorph/reconcile/compare.py
  src/databricks/labs/remorph/reconcile/connectors/snowflake.py
  src/databricks/labs/remorph/reconcile/exception.py
  src/databricks/labs/remorph/reconcile/execute.py
  src/databricks/labs/remorph/reconcile/recon_capture.py
  tests/unit/reconcile/test_compare.py
  tests/unit/reconcile/test_execute.py
  tests/unit/reconcile/test_recon_capture.py
Labels: internal

#437 Grammar clean up and keyword expansion
  core/src/main/antlr4/com/databricks/labs/remorph/parsers/snowflake/SnowflakeParser.g4
  core/src/main/antlr4/com/databricks/labs/remorph/parsers/tsql/TSqlLexer.g4
  core/src/main/antlr4/com/databricks/labs/remorph/parsers/tsql/TSqlParser.g4
  core/src/test/scala/com/databricks/labs/remorph/parsers/snowflake/SnowflakeAstBuilderSpec.scala
  core/src/test/scala/com/databricks/labs/remorph/parsers/tsql/TSqlAstBuilderSpec.scala
Labels: internal

#442 Snowflake: Improve translation of FROM clauses
  core/src/main/antlr4/com/databricks/labs/remorph/parsers/snowflake/SnowflakeParser.g4
  core/src/main/scala/com/databricks/labs/remorph/parsers/snowflake/SnowflakeRelationBuilder.scala
  core/src/test/scala/com/databricks/labs/remorph/parsers/snowflake/SnowflakeRelationBuilderSpec.scala
Labels: internal

#443 TSQL: Implement WITH CTE
  core/src/main/antlr4/com/databricks/labs/remorph/parsers/tsql/TSqlParser.g4
  core/src/main/scala/com/databricks/labs/remorph/parsers/snowflake/SnowflakeDDLBuilder.scala
  core/src/main/scala/com/databricks/labs/remorph/parsers/snowflake/SnowflakeExpressionBuilder.scala
  core/src/main/scala/com/databricks/labs/remorph/parsers/snowflake/SnowflakeRelationBuilder.scala
  core/src/main/scala/com/databricks/labs/remorph/parsers/tsql/TSqlExpressionBuilder.scala
  core/src/main/scala/com/databricks/labs/remorph/parsers/tsql/TSqlRelationBuilder.scala
  core/src/test/scala/com/databricks/labs/remorph/parsers/snowflake/SnowflakeExprSpec.scala
  core/src/test/scala/com/databricks/labs/remorph/parsers/snowflake/SnowflakeExpressionBuilderSpec.scala
  core/src/test/scala/com/databricks/labs/remorph/parsers/tsql/TSqlAstBuilderSpec.scala
  core/src/test/scala/com/databricks/labs/remorph/parsers/tsql/TSqlExpressionBuilderSpec.scala
  core/src/test/scala/com/databricks/labs/remorph/parsers/tsql/TSqlFunctionSpec.scala
  tests/resources/functional/tsql/select/test_cte_1.sql
  tests/resources/functional/tsql/select/test_cte_2.sql
Labels: pr/ready-to-merge

#433 Snowflake add missing function definitions
  core/src/main/antlr4/com/databricks/labs/remorph/parsers/snowflake/SnowflakeParser.g4
  core/src/main/scala/com/databricks/labs/remorph/parsers/FunctionBuilder.scala
  core/src/main/scala/com/databricks/labs/remorph/parsers/snowflake/SnowflakeExpressionBuilder.scala
  core/src/main/scala/com/databricks/labs/remorph/parsers/snowflake/SnowflakeFunctionBuilder.scala
  core/src/main/scala/com/databricks/labs/remorph/parsers/snowflake/SnowflakeRelationBuilder.scala
  core/src/test/scala/com/databricks/labs/remorph/parsers/common/FunctionBuilderSpec.scala
  core/src/test/scala/com/databricks/labs/remorph/parsers/snowflake/SnowflakeAstBuilderSpec.scala
  core/src/test/scala/com/databricks/labs/remorph/parsers/snowflake/SnowflakeExpressionBuilderSpec.scala
  core/src/test/scala/com/databricks/labs/remorph/parsers/snowflake/SnowflakeRelationBuilderSpec.scala
Labels: internal

#445 Lose superflous alt in selectListElem
  core/src/main/antlr4/com/databricks/labs/remorph/parsers/tsql/TSqlParser.g4
  core/src/main/scala/com/databricks/labs/remorph/parsers/tsql/TSqlExpressionBuilder.scala
  core/src/test/scala/com/databricks/labs/remorph/parsers/tsql/TSqlAstBuilderSpec.scala
  core/src/test/scala/com/databricks/labs/remorph/parsers/tsql/TSqlExpressionBuilderSpec.scala
Labels: internal, pr/ready-to-merge

#446 Snowflake: Implement SAMPLE clause
  core/src/main/antlr4/com/databricks/labs/remorph/parsers/snowflake/SnowflakeParser.g4
  core/src/main/scala/com/databricks/labs/remorph/parsers/intermediate/extensions.scala
  core/src/main/scala/com/databricks/labs/remorph/parsers/snowflake/SnowflakeRelationBuilder.scala
  core/src/test/scala/com/databricks/labs/remorph/parsers/snowflake/SnowflakeRelationBuilderSpec.scala
Labels: internal

#447 Snowflake: consider DUMMY as not a keyword
  core/src/main/antlr4/com/databricks/labs/remorph/parsers/snowflake/SnowflakeParser.g4
Labels: internal

#449 Snowflake:: Snowflake grammar clean up
  core/src/main/antlr4/com/databricks/labs/remorph/parsers/snowflake/SnowflakeParser.g4
  core/src/main/scala/com/databricks/labs/remorph/parsers/snowflake/DataTypeBuilder.scala
  core/src/main/scala/com/databricks/labs/remorph/parsers/snowflake/SnowflakeAstBuilder.scala
  core/src/main/scala/com/databricks/labs/remorph/parsers/snowflake/SnowflakeDDLBuilder.scala
  core/src/main/scala/com/databricks/labs/remorph/parsers/snowflake/SnowflakeExpressionBuilder.scala
  core/src/main/scala/com/databricks/labs/remorph/parsers/snowflake/SnowflakeRelationBuilder.scala
  core/src/test/scala/com/databricks/labs/remorph/parsers/snowflake/DataTypeBuilderSpec.scala
  core/src/test/scala/com/databricks/labs/remorph/parsers/snowflake/SnowflakeAstBuilderSpec.scala
  core/src/test/scala/com/databricks/labs/remorph/parsers/snowflake/SnowflakeDDLBuilderSpec.scala
  core/src/test/scala/com/databricks/labs/remorph/parsers/snowflake/SnowflakeExpressionBuilderSpec.scala
  core/src/test/scala/com/databricks/labs/remorph/parsers/snowflake/SnowflakeRelationBuilderSpec.scala
  coverage/src/main/scala/com/databricks/labs/remorph/coverage/QueryRunner.scala
Labels: internal

#456 Better coverage reports
  .github/workflows/push.yml
  coverage/pom.xml
  coverage/src/main/scala/com/databricks/labs/remorph/coverage/Main.scala
  coverage/src/main/scala/com/databricks/labs/remorph/coverage/QueryExtractor.scala
  coverage/src/test/scala/com/databricks/labs/remorph/coverage/AcceptanceTestRunner.scala
  tests/resources/functional/tsql/functions/test_get_bit_1.sql
Labels: internal

#455 TSQL: Improve function coverage
  core/src/main/antlr4/com/databricks/labs/remorph/parsers/tsql/TSqlLexer.g4
  core/src/main/antlr4/com/databricks/labs/remorph/parsers/tsql/TSqlParser.g4
  core/src/main/scala/com/databricks/labs/remorph/parsers/ConversionStrategy.scala
  core/src/main/scala/com/databricks/labs/remorph/parsers/FunctionBuilder.scala
  core/src/main/scala/com/databricks/labs/remorph/parsers/snowflake/SnowflakeFunctionBuilder.scala
  core/src/main/scala/com/databricks/labs/remorph/parsers/tsql/TSqlExpressionBuilder.scala
  core/src/main/scala/com/databricks/labs/remorph/parsers/tsql/TSqlFunctionBuilder.scala
  core/src/test/scala/com/databricks/labs/remorph/parsers/common/FunctionBuilderSpec.scala
  core/src/test/scala/com/databricks/labs/remorph/parsers/tsql/TSqlFunctionSpec.scala
  tests/resources/functional/tsql/functions/test_approx_percentile_cont_1.sql
  tests/resources/functional/tsql/functions/test_get_bit_1.sql
  tests/resources/functional/tsql/functions/test_left_shift_1.sql
  tests/resources/functional/tsql/functions/test_percentile_cont_1.sql
  tests/resources/functional/tsql/functions/test_right_shift_1.sql
  tests/resources/functional/tsql/functions/test_set_bit_1.sql
  tests/resources/functional/tsql/functions/test_set_bit_2.sql
Labels: internal

#459 Snowflake: improve id definition and related implementations
  core/src/main/antlr4/com/databricks/labs/remorph/parsers/snowflake/SnowflakeLexer.g4
  core/src/main/antlr4/com/databricks/labs/remorph/parsers/snowflake/SnowflakeParser.g4
  core/src/main/scala/com/databricks/labs/remorph/parsers/intermediate/extensions.scala
  core/src/main/scala/com/databricks/labs/remorph/parsers/snowflake/SnowflakeDDLBuilder.scala
  core/src/main/scala/com/databricks/labs/remorph/parsers/snowflake/SnowflakeExpressionBuilder.scala
  core/src/main/scala/com/databricks/labs/remorph/parsers/snowflake/SnowflakeRelationBuilder.scala
  core/src/main/scala/com/databricks/labs/remorph/parsers/snowflake/package.scala
  core/src/test/scala/com/databricks/labs/remorph/parsers/ParserTestCommon.scala
  core/src/test/scala/com/databricks/labs/remorph/parsers/snowflake/SnowflakeAstBuilderSpec.scala
  core/src/test/scala/com/databricks/labs/remorph/parsers/snowflake/SnowflakeDDLBuilderSpec.scala
  core/src/test/scala/com/databricks/labs/remorph/parsers/snowflake/SnowflakeExpressionBuilderSpec.scala
  core/src/test/scala/com/databricks/labs/remorph/parsers/snowflake/SnowflakeRelationBuilderSpec.scala
Labels: internal

#460 Add lexer tests for TSql and Snowflake lexers
  core/pom.xml
  core/src/main/antlr4/com/databricks/labs/remorph/parsers/snowflake/SnowflakeLexer.g4
  core/src/main/antlr4/com/databricks/labs/remorph/parsers/snowflake/SnowflakeParser.g4
  core/src/main/antlr4/com/databricks/labs/remorph/parsers/tsql/TSqlLexer.g4
  core/src/main/antlr4/com/databricks/labs/remorph/parsers/tsql/TSqlParser.g4
  core/src/test/scala/com/databricks/labs/remorph/parsers/snowflake/SnowLexerSpec.scala
  core/src/test/scala/com/databricks/labs/remorph/parsers/tsql/TSqlLexerSpec.scala
Labels: internal

#467 fix: Change order of search for "" in quoted lexer rule.
  core/src/main/antlr4/com/databricks/labs/remorph/parsers/snowflake/SnowflakeLexer.g4
  core/src/main/antlr4/com/databricks/labs/remorph/parsers/tsql/TSqlLexer.g4
  core/src/test/scala/com/databricks/labs/remorph/parsers/snowflake/SnowLexerSpec.scala
  core/src/test/scala/com/databricks/labs/remorph/parsers/tsql/TSqlLexerSpec.scala
Labels: internal

#461 Simplify the lexers and parsers by removing all unnecessary lexer tokens
  core/src/main/antlr4/com/databricks/labs/remorph/parsers/snowflake/SnowflakeLexer.g4
  core/src/main/antlr4/com/databricks/labs/remorph/parsers/tsql/TSqlLexer.g4
  core/src/main/antlr4/com/databricks/labs/remorph/parsers/tsql/TSqlParser.g4
  core/src/main/scala/com/databricks/labs/remorph/parsers/GenericOption.scala
  core/src/main/scala/com/databricks/labs/remorph/parsers/intermediate/extensions.scala
  core/src/main/scala/com/databricks/labs/remorph/parsers/tsql/TSqlAstBuilder.scala
  core/src/main/scala/com/databricks/labs/remorph/parsers/tsql/TSqlExpressionBuilder.scala
  core/src/test/scala/com/databricks/labs/remorph/parsers/tsql/TSqlAstBuilderSpec.scala
  core/src/test/scala/com/databricks/labs/remorph/parsers/tsql/TSqlExpressionBuilderSpec.scala
Labels: internal

#480 Added Databricks as source benchmarks
  README.md
Labels: internal

#479 Adding default transformations to join columns in hash query
  src/databricks/labs/remorph/reconcile/query_builder/hash_query.py
  tests/unit/reconcile/query_builder/test_hash_query.py
  tests/unit/reconcile/test_execute.py
Labels: internal

#471 Improve id definition and translations
  core/src/main/antlr4/com/databricks/labs/remorph/parsers/snowflake/SnowflakeParser.g4
  core/src/main/scala/com/databricks/labs/remorph/parsers/FunctionBuilder.scala
  core/src/main/scala/com/databricks/labs/remorph/parsers/intermediate/expressions.scala
  core/src/main/scala/com/databricks/labs/remorph/parsers/intermediate/extensions.scala
  core/src/main/scala/com/databricks/labs/remorph/parsers/intermediate/relations.scala
  core/src/main/scala/com/databricks/labs/remorph/parsers/snowflake/SnowflakeExpressionBuilder.scala
  core/src/main/scala/com/databricks/labs/remorph/parsers/snowflake/SnowflakeRelationBuilder.scala
  core/src/main/scala/com/databricks/labs/remorph/parsers/snowflake/package.scala
  core/src/main/scala/com/databricks/labs/remorph/parsers/tsql/TSqlExpressionBuilder.scala
  core/src/main/scala/com/databricks/labs/remorph/parsers/tsql/TSqlRelationBuilder.scala
  core/src/test/scala/com/databricks/labs/remorph/parsers/IRHelpers.scala
  core/src/test/scala/com/databricks/labs/remorph/parsers/ParserTestCommon.scala
  core/src/test/scala/com/databricks/labs/remorph/parsers/common/FunctionBuilderSpec.scala
  core/src/test/scala/com/databricks/labs/remorph/parsers/snowflake/SnowflakeAstBuilderSpec.scala
  core/src/test/scala/com/databricks/labs/remorph/parsers/snowflake/SnowflakeExprSpec.scala
  core/src/test/scala/com/databricks/labs/remorph/parsers/snowflake/SnowflakeExpressionBuilderSpec.scala
  core/src/test/scala/com/databricks/labs/remorph/parsers/snowflake/SnowflakeRelationBuilderSpec.scala
  core/src/test/scala/com/databricks/labs/remorph/parsers/tsql/TSqlAstBuilderSpec.scala
  core/src/test/scala/com/databricks/labs/remorph/parsers/tsql/TSqlExpressionBuilderSpec.scala
  core/src/test/scala/com/databricks/labs/remorph/parsers/tsql/TSqlFunctionSpec.scala
  core/src/test/scala/com/databricks/labs/remorph/parsers/tsql/TSqlRelationBuilderSpec.scala
Labels: internal

#475 feat: Implement syntax for windowing functions over clause
  core/src/main/antlr4/com/databricks/labs/remorph/parsers/snowflake/SnowflakeLexer.g4
  core/src/main/antlr4/com/databricks/labs/remorph/parsers/snowflake/SnowflakeParser.g4
  core/src/main/scala/com/databricks/labs/remorph/parsers/intermediate/expressions.scala
  core/src/main/scala/com/databricks/labs/remorph/parsers/snowflake/SnowflakeExpressionBuilder.scala
  core/src/main/scala/com/databricks/labs/remorph/parsers/snowflake/SnowflakeRelationBuilder.scala
  core/src/main/scala/com/databricks/labs/remorph/parsers/snowflake/package.scala
  core/src/main/scala/com/databricks/labs/remorph/parsers/tsql/TSqlExpressionBuilder.scala
  core/src/test/scala/com/databricks/labs/remorph/parsers/snowflake/SnowflakeAstBuilderSpec.scala
  core/src/test/scala/com/databricks/labs/remorph/parsers/snowflake/SnowflakeExpressionBuilderSpec.scala
  core/src/test/scala/com/databricks/labs/remorph/parsers/snowflake/SnowflakeRelationBuilderSpec.scala
  core/src/test/scala/com/databricks/labs/remorph/parsers/tsql/TSqlAstBuilderSpec.scala
  core/src/test/scala/com/databricks/labs/remorph/parsers/tsql/TSqlExpressionBuilderSpec.scala
  core/src/test/scala/com/databricks/labs/remorph/parsers/tsql/TSqlFunctionSpec.scala
Labels: internal

#482 Add more coverage for TSQL
  core/src/main/antlr4/com/databricks/labs/remorph/parsers/tsql/TSqlLexer.g4
  core/src/main/antlr4/com/databricks/labs/remorph/parsers/tsql/TSqlParser.g4
  core/src/main/scala/com/databricks/labs/remorph/parsers/tsql/TSqlFunctionBuilder.scala
  core/src/test/scala/com/databricks/labs/remorph/parsers/common/FunctionBuilderSpec.scala
  core/src/test/scala/com/databricks/labs/remorph/parsers/tsql/TSqlFunctionBuilderSpec.scala
  tests/resources/functional/tsql/functions/test_aadbts_1.sql
  tests/resources/functional/tsql/functions/test_aalangid1.sql
  tests/resources/functional/tsql/functions/test_aalanguage_1.sql
  tests/resources/functional/tsql/functions/test_aalock_timeout_1.sql
  tests/resources/functional/tsql/functions/test_aamax_connections_1.sql
  tests/resources/functional/tsql/functions/test_aamax_precision_1.sql
  tests/resources/functional/tsql/functions/test_aaoptions_1.sql
  tests/resources/functional/tsql/functions/test_aaremserver_1.sql
  tests/resources/functional/tsql/functions/test_aaservername_1.sql
  tests/resources/functional/tsql/functions/test_aaservicename_1.sql
  tests/resources/functional/tsql/functions/test_aaspid_1.sql
  tests/resources/functional/tsql/functions/test_aatextsize_1.sql
  tests/resources/functional/tsql/functions/test_aaversion_1.sql
  tests/resources/functional/tsql/functions/test_collationproperty_1.sql
  tests/resources/functional/tsql/functions/test_nestlevel_1.sql
Labels: internal

#481 Clean up grammar format, remove some redundant labels
  core/src/main/antlr4/com/databricks/labs/remorph/parsers/snowflake/SnowflakeLexer.g4
  core/src/main/antlr4/com/databricks/labs/remorph/parsers/snowflake/SnowflakeParser.g4
  core/src/main/antlr4/com/databricks/labs/remorph/parsers/tsql/TSqlLexer.g4
  core/src/main/antlr4/com/databricks/labs/remorph/parsers/tsql/TSqlParser.g4
Labels: internal

#485 Improve Snowflake coverage test success rate
  core/src/main/antlr4/com/databricks/labs/remorph/parsers/snowflake/SnowflakeLexer.g4
  core/src/main/antlr4/com/databricks/labs/remorph/parsers/snowflake/SnowflakeParser.g4
  core/src/main/scala/com/databricks/labs/remorph/parsers/snowflake/SnowflakeFunctionBuilder.scala
  core/src/test/scala/com/databricks/labs/remorph/parsers/common/FunctionBuilderSpec.scala
  tests/resources/functional/snowflake/test_array_position/test_array_position_1.sql
  tests/resources/functional/snowflake/test_datediff/test_datediff_11.sql
  tests/resources/functional/snowflake/test_dense_rank/test_dense_rank_1.sql
  tests/resources/functional/snowflake/test_get/test_get_1.sql
  tests/resources/functional/snowflake/test_monthname/test_monthname_3.sql
  tests/resources/functional/snowflake/test_regexp_count/test_regexp_count_1.sql
  tests/resources/functional/snowflake/test_regexp_instr/test_regexp_instr_1.sql
Labels: internal

#487 feat: Implement freetext function visitor, simplify grammar
  core/src/main/antlr4/com/databricks/labs/remorph/parsers/tsql/TSqlParser.g4
  core/src/main/scala/com/databricks/labs/remorph/parsers/tsql/TSqlExpressionBuilder.scala
  core/src/main/scala/com/databricks/labs/remorph/parsers/tsql/TSqlFunctionBuilder.scala
  core/src/test/scala/com/databricks/labs/remorph/parsers/tsql/TSqlFunctionBuilderSpec.scala
  core/src/test/scala/com/databricks/labs/remorph/parsers/tsql/TSqlFunctionSpec.scala
Labels: internal

#491 Added benchmark's for snowflake as source
  README.md
Labels: internal

#489 Snowflake, improve coverage test success rate
  core/src/main/antlr4/com/databricks/labs/remorph/parsers/snowflake/SnowflakeLexer.g4
  core/src/main/antlr4/com/databricks/labs/remorph/parsers/snowflake/SnowflakeParser.g4
  core/src/main/scala/com/databricks/labs/remorph/parsers/intermediate/extensions.scala
  core/src/main/scala/com/databricks/labs/remorph/parsers/snowflake/SnowflakeExpressionBuilder.scala
  core/src/main/scala/com/databricks/labs/remorph/parsers/snowflake/SnowflakeFunctionBuilder.scala
  core/src/main/scala/com/databricks/labs/remorph/parsers/snowflake/SnowflakeRelationBuilder.scala
  core/src/test/scala/com/databricks/labs/remorph/parsers/common/FunctionBuilderSpec.scala
  core/src/test/scala/com/databricks/labs/remorph/parsers/snowflake/SnowflakeExprSpec.scala
  core/src/test/scala/com/databricks/labs/remorph/parsers/snowflake/SnowflakeExpressionBuilderSpec.scala
  core/src/test/scala/com/databricks/labs/remorph/parsers/snowflake/SnowflakeRelationBuilderSpec.scala
  coverage/src/main/scala/com/databricks/labs/remorph/coverage/QueryExtractor.scala
  coverage/src/test/scala/com/databricks/labs/remorph/coverage/AcceptanceTestRunner.scala
  tests/resources/functional/snowflake/test_array_cat/test_array_cat_2.sql
  tests/resources/functional/snowflake/test_nth_value/test_nth_value_1.sql
Labels: internal

#494 Snowflake: pull conversion functions out of cast expressions
  core/src/main/antlr4/com/databricks/labs/remorph/parsers/snowflake/SnowflakeLexer.g4
  core/src/main/antlr4/com/databricks/labs/remorph/parsers/snowflake/SnowflakeParser.g4
  core/src/main/scala/com/databricks/labs/remorph/parsers/snowflake/SnowflakeExpressionBuilder.scala
  core/src/main/scala/com/databricks/labs/remorph/parsers/snowflake/SnowflakeFunctionBuilder.scala
  core/src/test/scala/com/databricks/labs/remorph/parsers/common/FunctionBuilderSpec.scala
  core/src/test/scala/com/databricks/labs/remorph/parsers/snowflake/SnowflakeExprSpec.scala
Labels: internal
