Repository databrickslabs/lakebridge, pull requests merged in 2024-09, with the labels that each got.

#882 Add basis of ANTLR utilities, starting with text extractor
  core/src/main/scala/com/databricks/labs/remorph/parsers/ParserCommon.scala
  core/src/test/scala/com/databricks/labs/remorph/parsers/VisitorsSpec.scala
Labels: internal, antlr

#875 Updated Spark setup script
  .github/scripts/setup_spark_remote.sh
Labels: internal

#864 unresolved commands `alter session | stream...` `create stream` `create task`
  core/src/main/scala/com/databricks/labs/remorph/parsers/intermediate/unresolved.scala
  core/src/main/scala/com/databricks/labs/remorph/parsers/snowflake/SnowflakeDDLBuilder.scala
  core/src/test/scala/com/databricks/labs/remorph/parsers/snowflake/SnowflakeDDLBuilderSpec.scala
  tests/resources/functional/snowflake/test_skip_unsupported_operations/test_skip_unsupported_operations_5.sql
  tests/resources/functional/snowflake/test_skip_unsupported_operations/test_skip_unsupported_operations_9.sql
Labels: internal

#887 Fix Query Generation IR for Select Distinct
  core/src/main/scala/com/databricks/labs/remorph/parsers/intermediate/relations.scala
  core/src/main/scala/com/databricks/labs/remorph/parsers/snowflake/SnowflakeRelationBuilder.scala
  core/src/test/scala/com/databricks/labs/remorph/parsers/snowflake/SnowflakeRelationBuilderSpec.scala
  core/src/test/scala/com/databricks/labs/remorph/transpilers/SnowflakeToDatabricksTranspilerTest.scala
  src/databricks/labs/remorph/snow/databricks.py
  tests/resources/functional/snowflake/test_skip_unsupported_operations/test_skip_unsupported_operations_11.sql
  tests/unit/snow/test_snow.py
Labels: feat/ir

#899 Make CallMapper a Rule[LogicalPlan]
  core/src/main/scala/com/databricks/labs/remorph/generators/sql/ExpressionGenerator.scala
  core/src/main/scala/com/databricks/labs/remorph/parsers/intermediate/functions.scala
  core/src/main/scala/com/databricks/labs/remorph/transpilers/SnowflakeToDatabricksTranspiler.scala
  core/src/main/scala/com/databricks/labs/remorph/transpilers/TSqlToDatabricksTranspiler.scala
  core/src/test/scala/com/databricks/labs/remorph/generators/sql/ExpressionGeneratorTest.scala
  core/src/test/scala/com/databricks/labs/remorph/parsers/tsql/TSqlExpressionGeneratorTest.scala
  core/src/test/scala/com/databricks/labs/remorph/parsers/tsql/rules/TSqlCallMapperSpec.scala
Labels: internal

#777 Upgrade script Implementation
  src/databricks/labs/remorph/contexts/application.py
  src/databricks/labs/remorph/deployment/installation.py
  src/databricks/labs/remorph/install.py
  src/databricks/labs/remorph/resources/reconcile/queries/installation/main.sql
  src/databricks/labs/remorph/upgrades/v0.4.0_add_main_table_operation_name_column.py
  tests/unit/deployment/test_installation.py
  tests/unit/test_install.py
Labels: enhancement

#911 TSQL: Implement CREATE TABLE
  core/src/main/antlr4/com/databricks/labs/remorph/parsers/tsql/TSqlLexer.g4
  core/src/main/antlr4/com/databricks/labs/remorph/parsers/tsql/TSqlParser.g4
  core/src/main/scala/com/databricks/labs/remorph/generators/sql/LogicalPlanGenerator.scala
  core/src/main/scala/com/databricks/labs/remorph/generators/sql/OptionGenerator.scala
  core/src/main/scala/com/databricks/labs/remorph/parsers/GenericOption.scala
  core/src/main/scala/com/databricks/labs/remorph/parsers/intermediate/ddl.scala
  core/src/main/scala/com/databricks/labs/remorph/parsers/intermediate/extensions.scala
  core/src/main/scala/com/databricks/labs/remorph/parsers/intermediate/unresolved.scala
  core/src/main/scala/com/databricks/labs/remorph/parsers/snowflake/SnowflakeDDLBuilder.scala
  core/src/main/scala/com/databricks/labs/remorph/parsers/tsql/TSqlAstBuilder.scala
  core/src/main/scala/com/databricks/labs/remorph/parsers/tsql/TSqlDDLBuilder.scala
  core/src/main/scala/com/databricks/labs/remorph/parsers/tsql/TSqlExpressionBuilder.scala
  core/src/main/scala/com/databricks/labs/remorph/parsers/tsql/TSqlRelationBuilder.scala
  core/src/main/scala/com/databricks/labs/remorph/parsers/tsql/relations.scala
  core/src/main/scala/com/databricks/labs/remorph/transpilers/SnowflakeToDatabricksTranspiler.scala
  core/src/main/scala/com/databricks/labs/remorph/transpilers/TSqlToDatabricksTranspiler.scala
  core/src/main/scala/com/databricks/labs/remorph/utils/ParsingUtils.scala
  core/src/test/scala/com/databricks/labs/remorph/generators/sql/DataTypeGeneratorTest.scala
  core/src/test/scala/com/databricks/labs/remorph/generators/sql/GeneratorTestCommon.scala
  core/src/test/scala/com/databricks/labs/remorph/generators/sql/LogicalPlanGeneratorTest.scala
  core/src/test/scala/com/databricks/labs/remorph/parsers/snowflake/SnowflakeDDLBuilderSpec.scala
  core/src/test/scala/com/databricks/labs/remorph/parsers/tsql/TSqkDDLBuilderSpec.scala
Labels: feat/ir, sql/tsql, ir/ddl, antlr

#881 Chore/other command
  core/src/main/scala/com/databricks/labs/remorph/generators/sql/LogicalPlanGenerator.scala
  core/src/main/scala/com/databricks/labs/remorph/parsers/intermediate/commands.scala
  core/src/main/scala/com/databricks/labs/remorph/parsers/snowflake/SnowflakeAstBuilder.scala
  core/src/main/scala/com/databricks/labs/remorph/parsers/snowflake/SnowflakeCommandBuilder.scala
  core/src/test/scala/com/databricks/labs/remorph/discovery/AnonymizerTest.scala
  core/src/test/scala/com/databricks/labs/remorph/transpilers/SnowflakeToDatabricksTranspilerTest.scala
Labels: internal

#884 updated remorph reconcile workflow to use wheels instead of pypi
  src/databricks/labs/remorph/deployment/installation.py
  src/databricks/labs/remorph/deployment/job.py
  src/databricks/labs/remorph/deployment/recon.py
  src/databricks/labs/remorph/upgrades/v0.4.0_add_main_table_operation_name_column.py
  tests/unit/deployment/test_job.py
  tests/unit/deployment/test_recon.py
Labels: feat/recon

#888 Create more robust toolchain control with error recording for repeatable testing
  core/src/main/scala/com/databricks/labs/remorph/discovery/Anonymizer.scala
  core/src/main/scala/com/databricks/labs/remorph/parsers/PlanParser.scala
  core/src/main/scala/com/databricks/labs/remorph/parsers/snowflake/SnowflakePlanParser.scala
  core/src/main/scala/com/databricks/labs/remorph/parsers/tsql/TSqlPlanParser.scala
  core/src/main/scala/com/databricks/labs/remorph/queries/QueryExtractor.scala
  core/src/main/scala/com/databricks/labs/remorph/transpilers/Result.scala
  core/src/main/scala/com/databricks/labs/remorph/transpilers/SnowflakeToDatabricksTranspiler.scala
  core/src/main/scala/com/databricks/labs/remorph/transpilers/Source.scala
  core/src/main/scala/com/databricks/labs/remorph/transpilers/TSqlToDatabricksTranspiler.scala
  core/src/main/scala/com/databricks/labs/remorph/transpilers/Transpiler.scala
  core/src/test/resources/toolchain/testsource/not_sql.md
  core/src/test/resources/toolchain/testsource/test_1.sql
  core/src/test/resources/toolchain/testsource/test_2.sql
  core/src/test/resources/toolchain/testsource/test_3.sql
  core/src/test/scala/com/databricks/labs/remorph/discovery/AnonymizerTest.scala
  core/src/test/scala/com/databricks/labs/remorph/queries/ExampleDebuggerTest.scala
  core/src/test/scala/com/databricks/labs/remorph/transpilers/SnowflakeToDatabricksTranspilerTest.scala
  core/src/test/scala/com/databricks/labs/remorph/transpilers/TranspilerTestCommon.scala
  core/src/test/scala/toolchain/ToolchainSpec.scala
  coverage/src/main/scala/com/databricks/labs/remorph/coverage/QueryRunner.scala
Labels: enhancement, internal

#904 Fetch TableDefinitions from Snowflake
  core/src/main/scala/com/databricks/labs/remorph/discovery/SnowflakeTableDefinitions.scala
  core/src/test/scala/com/databricks/labs/remorph/discovery/SnowflakeTableDefinitionTest.scala
Labels: feat/history

#915 TSQL: Reorg of DML IR and generation production after CREATE TABLE
  core/src/main/antlr4/com/databricks/labs/remorph/parsers/tsql/TSqlParser.g4
  core/src/main/scala/com/databricks/labs/remorph/parsers/PlanParser.scala
  core/src/main/scala/com/databricks/labs/remorph/parsers/VisitorCoordinator.scala
  core/src/main/scala/com/databricks/labs/remorph/parsers/intermediate/unresolved.scala
  core/src/main/scala/com/databricks/labs/remorph/parsers/snowflake/SnowflakePlanParser.scala
  core/src/main/scala/com/databricks/labs/remorph/parsers/tsql/OptionBuilder.scala
  core/src/main/scala/com/databricks/labs/remorph/parsers/tsql/TSqlAstBuilder.scala
  core/src/main/scala/com/databricks/labs/remorph/parsers/tsql/TSqlDDLBuilder.scala
  core/src/main/scala/com/databricks/labs/remorph/parsers/tsql/TSqlDMLBuilder.scala
  core/src/main/scala/com/databricks/labs/remorph/parsers/tsql/TSqlExpressionBuilder.scala
  core/src/main/scala/com/databricks/labs/remorph/parsers/tsql/TSqlPlanParser.scala
  core/src/main/scala/com/databricks/labs/remorph/parsers/tsql/TSqlRelationBuilder.scala
  core/src/main/scala/com/databricks/labs/remorph/parsers/tsql/TSqlVisitorCoordinator.scala
  core/src/main/scala/com/databricks/labs/remorph/parsers/tsql/relations.scala
  core/src/test/scala/com/databricks/labs/remorph/parsers/tsql/TSqlAstBuilderSpec.scala
  core/src/test/scala/com/databricks/labs/remorph/parsers/tsql/TSqlDDLBuilderSpec.scala
  core/src/test/scala/com/databricks/labs/remorph/parsers/tsql/TSqlErrorStategySpec.scala
  core/src/test/scala/com/databricks/labs/remorph/parsers/tsql/TSqlExpressionBuilderSpec.scala
  core/src/test/scala/com/databricks/labs/remorph/parsers/tsql/TSqlExpressionGeneratorTest.scala
  core/src/test/scala/com/databricks/labs/remorph/parsers/tsql/TSqlFunctionSpec.scala
  core/src/test/scala/com/databricks/labs/remorph/parsers/tsql/TSqlParserTestCommon.scala
  core/src/test/scala/com/databricks/labs/remorph/parsers/tsql/TSqlRelationBuilderSpec.scala
Labels: enhancement, feat/ir, internal, sql/tsql, antlr

#925 Patch Pylint to fixed version 3.2.2
  pyproject.toml
Labels: internal

#922 feat: Implement all of TSQL predicates except for SOME ALL ANY
  core/src/main/antlr4/com/databricks/labs/remorph/parsers/tsql/TSqlParser.g4
  core/src/main/scala/com/databricks/labs/remorph/generators/sql/ExpressionGenerator.scala
  core/src/main/scala/com/databricks/labs/remorph/parsers/intermediate/operators.scala
  core/src/main/scala/com/databricks/labs/remorph/parsers/snowflake/SnowflakeExpressionBuilder.scala
  core/src/main/scala/com/databricks/labs/remorph/parsers/tsql/TSqlAstBuilder.scala
  core/src/main/scala/com/databricks/labs/remorph/parsers/tsql/TSqlDDLBuilder.scala
  core/src/main/scala/com/databricks/labs/remorph/parsers/tsql/TSqlDMLBuilder.scala
  core/src/main/scala/com/databricks/labs/remorph/parsers/tsql/TSqlExpressionBuilder.scala
  core/src/main/scala/com/databricks/labs/remorph/parsers/tsql/TSqlRelationBuilder.scala
  core/src/test/scala/com/databricks/labs/remorph/generators/sql/ExpressionGeneratorTest.scala
  core/src/test/scala/com/databricks/labs/remorph/parsers/snowflake/SnowflakeExprSpec.scala
  core/src/test/scala/com/databricks/labs/remorph/parsers/tsql/TSqlDDLBuilderSpec.scala
Labels: feat/ir, sql/tsql, ir/dml, antlr

#920 Ensure that successful parsing is recorded even if transpilation fails and record reconciled generations
  coverage/src/main/scala/com/databricks/labs/remorph/coverage/QueryRunner.scala
  src/databricks/labs/remorph/coverage/commons.py
Labels: bug, internal

#931 Added documentation for Reconcile authentication keys
  README.md
Labels: documentation, internal

#912 Move coverage tests into the core module
  .github/workflows/push.yml
  Makefile
  core/pom.xml
  core/src/main/scala/com/databricks/labs/remorph/ApplicationContext.scala
  core/src/main/scala/com/databricks/labs/remorph/Main.scala
  core/src/main/scala/com/databricks/labs/remorph/coverage/AcceptanceTestRunner.scala
  core/src/main/scala/com/databricks/labs/remorph/coverage/CoverageTest.scala
  core/src/main/scala/com/databricks/labs/remorph/coverage/QueryRunner.scala
  core/src/main/scala/com/databricks/labs/remorph/coverage/ReportEntry.scala
  core/src/main/scala/com/databricks/labs/remorph/coverage/runners/CsvDumper.scala
  core/src/main/scala/com/databricks/labs/remorph/coverage/runners/DatabricksSQL.scala
  core/src/main/scala/com/databricks/labs/remorph/coverage/runners/EnvGetter.scala
  core/src/main/scala/com/databricks/labs/remorph/coverage/runners/SnowflakeRunner.scala
  core/src/main/scala/com/databricks/labs/remorph/coverage/runners/TSqlRunner.scala
  core/src/main/scala/com/databricks/labs/remorph/parsers/ErrorCollector.scala
  core/src/test/scala/com/databricks/labs/remorph/coverage/AcceptanceSpec.scala
  core/src/test/scala/com/databricks/labs/remorph/coverage/AcceptanceTestRunner.scala
  core/src/test/scala/com/databricks/labs/remorph/coverage/runners/DatabricksSQLTest.scala
  core/src/test/scala/com/databricks/labs/remorph/coverage/runners/SnowflakeTest.scala
  core/src/test/scala/com/databricks/labs/remorph/coverage/runners/TSqlTest.scala
  core/src/test/scala/com/databricks/labs/remorph/integration/SnowflakeQueryHistoryTest.scala
  core/src/test/scala/com/databricks/labs/remorph/parsers/tsql/TSqlErrorHandlerSpec.scala
  coverage/pom.xml
  coverage/src/test/scala/com/databricks/labs/remorph/coverage/AcceptanceTestRunner.scala
  pom.xml
Labels: internal

#934 Created a mapping dict for algo for each dialect at layer level
  src/databricks/labs/remorph/reconcile/execute.py
  src/databricks/labs/remorph/reconcile/query_builder/expression_generator.py
  src/databricks/labs/remorph/reconcile/query_builder/hash_query.py
  src/databricks/labs/remorph/reconcile/recon_config.py
  tests/unit/reconcile/query_builder/test_expression_generator.py
Labels: do-not-merge

#924 Create repeatable estimator for Snowflake query history
  .github/workflows/push.yml
  Makefile
  core/src/main/scala/com/databricks/labs/remorph/ApplicationContext.scala
  core/src/main/scala/com/databricks/labs/remorph/Main.scala
  core/src/main/scala/com/databricks/labs/remorph/coverage/EstimationReport.scala
  core/src/main/scala/com/databricks/labs/remorph/coverage/connections/SnowflakeConnectionFactory.scala
  core/src/main/scala/com/databricks/labs/remorph/coverage/estimation/EstimationAnalyzer.scala
  core/src/main/scala/com/databricks/labs/remorph/coverage/estimation/EstimationReporter.scala
  core/src/main/scala/com/databricks/labs/remorph/coverage/estimation/Estimator.scala
  core/src/main/scala/com/databricks/labs/remorph/discovery/Anonymizer.scala
  core/src/main/scala/com/databricks/labs/remorph/discovery/SnowflakeQueryHistory.scala
  core/src/main/scala/com/databricks/labs/remorph/discovery/queries.scala
  core/src/main/scala/com/databricks/labs/remorph/parsers/PlanParser.scala
  core/src/main/scala/com/databricks/labs/remorph/parsers/snowflake/SnowflakePlanParser.scala
  core/src/main/scala/com/databricks/labs/remorph/parsers/tsql/TSqlPlanParser.scala
  core/src/main/scala/com/databricks/labs/remorph/transpilers/SqlGenerator.scala
  core/src/main/scala/com/databricks/labs/remorph/transpilers/Transpiler.scala
  core/src/test/scala/com/databricks/labs/remorph/coverage/EstimationTest.scala
  core/src/test/scala/com/databricks/labs/remorph/discovery/AnonymizerTest.scala
Labels: enhancement, sql/snowflake, estimate/transpile

#940 Make debug-coverage a proper command
  Makefile
  core/src/main/scala/com/databricks/labs/remorph/Main.scala
  core/src/main/scala/com/databricks/labs/remorph/coverage/CoverageTest.scala
  labs.yml
  src/databricks/labs/remorph/cli.py
Labels: internal

#937 Translation Complexity Analyzer
  core/src/main/scala/com/databricks/labs/remorph/ApplicationContext.scala
  core/src/main/scala/com/databricks/labs/remorph/Main.scala
  core/src/main/scala/com/databricks/labs/remorph/coverage/EstimationReport.scala
  core/src/main/scala/com/databricks/labs/remorph/coverage/estimation/EstimationAnalyzer.scala
  core/src/main/scala/com/databricks/labs/remorph/coverage/estimation/EstimationReporter.scala
  core/src/main/scala/com/databricks/labs/remorph/coverage/estimation/Estimator.scala
  core/src/main/scala/com/databricks/labs/remorph/discovery/Anonymizer.scala
  core/src/main/scala/com/databricks/labs/remorph/discovery/SnowflakeQueryHistory.scala
  core/src/test/scala/com/databricks/labs/remorph/discovery/AnonymizerTest.scala
Labels: enhancement, internal, sql/snowflake, estimate/transpile
