Repository databrickslabs/lakebridge, pull requests merged in 2025-02, with the labels that each got.

#1403 Added SQL Server reconcile code
  src/databricks/labs/remorph/reconcile/connectors/jdbc_reader.py
  src/databricks/labs/remorph/reconcile/connectors/source_adapter.py
  src/databricks/labs/remorph/reconcile/connectors/sql_server.py
  src/databricks/labs/remorph/reconcile/query_builder/expression_generator.py
  tests/unit/reconcile/connectors/test_sql_server.py
Labels: enhancement

#1436 Simplified installation journey
  labs.yml
  src/databricks/labs/remorph/base_install.py
  src/databricks/labs/remorph/cli.py
  src/databricks/labs/remorph/install.py
  tests/unit/test_install.py
Labels: internal

#1442 Removed unused Mode
  labs.yml
  src/databricks/labs/remorph/cli.py
  src/databricks/labs/remorph/config.py
  src/databricks/labs/remorph/install.py
  tests/unit/conftest.py
  tests/unit/contexts/test_application.py
  tests/unit/deployment/test_installation.py
  tests/unit/test_cli_transpile.py
  tests/unit/test_install.py
Labels: feat/cli, internal

#1441 added user agent for sub command
  src/databricks/labs/remorph/base_install.py
  src/databricks/labs/remorph/cli.py
Labels: internal

#1409 Improve implementation of storage of transpiled files
  src/databricks/labs/remorph/transpiler/execute.py
  src/databricks/labs/remorph/transpiler/lsp/lsp_engine.py
  src/databricks/labs/remorph/transpiler/sqlglot/sqlglot_engine.py
  tests/resources/lsp_transpiler/lsp_server.py
  tests/unit/conftest.py
  tests/unit/transpiler/test_execute.py
Labels: required for next release

#1432 install remorph-community-transpiler and morpheus
  src/databricks/labs/remorph/install.py
  src/databricks/labs/remorph/resources/transpilers/morpheus/config.yml
  src/databricks/labs/remorph/resources/transpilers/rct/config.yml
  src/databricks/labs/remorph/transpiler/lsp/lsp_engine.py
  tests/integration/test_install.py
  tests/resources/lsp_transpiler/lsp_config.yml
  tests/unit/test_install.py
  tests/unit/transpiler/test_lsp_config.py
Labels: required for next release

#1443 Feature local setup makefile
  CONTRIBUTING.md
  Makefile
Labels: do-not-merge

#1420 Initial Spec For Credential Management and SQLAlchemy Database Connectors
  .github/scripts/setup_mssql_odbc.sh
  .github/workflows/acceptance.yml
  Makefile
  pyproject.toml
  src/databricks/labs/remorph/connections/__init__.py
  src/databricks/labs/remorph/connections/credential_manager.py
  src/databricks/labs/remorph/connections/database_manager.py
  src/databricks/labs/remorph/connections/env_getter.py
  src/databricks/labs/remorph/resources/config/credentials.yml
  tests/integration/conftest.py
  tests/integration/connections/__init__.py
  tests/integration/connections/debug_envgetter.py
  tests/integration/connections/test_mssql_connector.py
  tests/unit/connections/test_credential_manager.py
  tests/unit/connections/test_database_manager.py
Labels: stacked PR, feature/profiler

#1387 Generate table properties if DDL contain default values
  core/src/main/scala/com/databricks/labs/remorph/generators/sql/LogicalPlanGenerator.scala
  core/src/test/scala/com/databricks/labs/remorph/transpilers/SnowflakeToDatabricksTranspilerTest.scala
  src/databricks/labs/remorph/transpiler/sqlglot/generator/databricks.py
  tests/resources/functional/snowflake/ddl/test_create_ddl_2.sql
  tests/resources/functional/teradata/ddl/test_table_properties.sql
Labels: enhancement

#1458 [BUG] Fix transpiler installer issue
  src/databricks/labs/remorph/install.py
  src/databricks/labs/remorph/resources/transpilers/morpheus/lib/config.yml
  src/databricks/labs/remorph/resources/transpilers/rct/lib/config.yml
  tests/integration/test_install.py
Labels: bug

#1457 Transpiler logging improvements
  src/databricks/labs/remorph/helpers/execution_time.py
  src/databricks/labs/remorph/transpiler/execute.py
  src/databricks/labs/remorph/transpiler/lsp/lsp_engine.py
Labels: enhancement, feat/cli
