Repository databrickslabs/lakebridge, pull requests merged in 2025-07, with the labels that each got.

#1780 Update `transpile` unit tests
  tests/unit/test_cli_transpile.py
Labels: tech debt, internal

#1784 Improve diagnostics if the Java check fails prior to installing morpheus
  src/databricks/labs/lakebridge/install.py
  tests/integration/install/test_installer.py
  tests/unit/test_install.py
Labels: enhancement

#1799 Add additional Telemetry
  src/databricks/labs/lakebridge/cli.py
Labels: feat/cli, internal

#1774 Patches End To End Install Test in main
  tests/integration/install/test_install_and_run.py
Labels: bug, tech debt, internal

#1802 Workaround issue loading transpiler configuration with python ≥ 3.12.4
  src/databricks/labs/lakebridge/config.py
  tests/unit/test_config.py
Labels: bug

#1637 Update CLI argument handling for `transpile`
  src/databricks/labs/lakebridge/cli.py
  src/databricks/labs/lakebridge/config.py
  src/databricks/labs/lakebridge/transpiler/execute.py
  src/databricks/labs/lakebridge/transpiler/lsp/lsp_engine.py
  src/databricks/labs/lakebridge/transpiler/sqlglot/sqlglot_engine.py
  src/databricks/labs/lakebridge/transpiler/transpile_engine.py
  tests/unit/conftest.py
  tests/unit/test_cli_lineage.py
  tests/unit/test_cli_transpile.py
  tests/unit/transpiler/test_execute.py
Labels: bug, enhancement, tech debt, fit&finish

#1828 Support conversion of XML files with internally-specified encoding
  .github/workflows/push.yml
  pyproject.toml
  src/databricks/labs/lakebridge/transpiler/execute.py
  tests/integration/transpile/test_bladebridge.py
  tests/integration/transpile/test_morpheus.py
  tests/resources/functional/informatica/wf_m_employees_load.XML
Labels: bug, dependencies, tech debt

#1838 Fix `transpile` when relative path is given for input sources
  src/databricks/labs/lakebridge/transpiler/lsp/lsp_engine.py
  tests/resources/lsp_transpiler/lsp_server.py
  tests/unit/conftest.py
  tests/unit/transpiler/test_lsp_engine.py
Labels: bug

#1847 Fix Acceptance Test
  .github/scripts/setup_mssql_odbc.sh
Labels: internal

#1842 Introducing Pandas Stubs
  Makefile
  pyproject.toml
  tests/integration/reconcile/query_builder/test_execute.py
  tests/integration/reconcile/test_aggregates_reconcile.py
  tests/integration/reconcile/test_compare.py
Labels: internal

#1850 Drop stray `print()`
  tests/unit/transpiler/test_sqlglot_engine.py
Labels: tech debt, internal

#1857 LSP (client) test improvements
  tests/unit/transpiler/test_lsp_engine.py
Labels: tech debt, internal

#1840 Bladebridge configs manual
  docs/lakebridge/docs/transpile/bladebridge_configuration.mdx
Labels: documentation

#1868 Chore Refactor Old Name
  src/databricks/labs/lakebridge/config.py
  src/databricks/labs/lakebridge/contexts/application.py
  src/databricks/labs/lakebridge/deployment/installation.py
  src/databricks/labs/lakebridge/install.py
  tests/unit/deployment/test_installation.py
  tests/unit/deployment/test_job.py
  tests/unit/deployment/test_recon.py
  tests/unit/test_install.py
  tests/unit/test_uninstall.py
Labels: tech debt, internal

#1878 Remove spurious warning during fresh `install-transpile`
  src/databricks/labs/lakebridge/deployment/installation.py
Labels: enhancement

#1879 Refactor transpiler repository
  src/databricks/labs/lakebridge/cli.py
  src/databricks/labs/lakebridge/install.py
  src/databricks/labs/lakebridge/transpiler/repository.py
  tests/integration/install/test_install_and_run.py
  tests/integration/install/test_installer.py
  tests/integration/transpile/test_bladebridge.py
  tests/integration/transpile/test_morpheus.py
  tests/integration/transpile/test_repository.py
  tests/unit/test_install.py
Labels: tech debt, internal

#1884 Updated config docs
  docs/lakebridge/docs/transpile/Pluggable transpilers/bladebridge_configuration.mdx
  docs/lakebridge/docs/transpile/Pluggable transpilers/bladebridge_overview.mdx
  docs/lakebridge/docs/transpile/Pluggable transpilers/index.mdx
Labels: documentation, bb converter
