Repository databrickslabs/lakebridge, pull requests merged in 2025-01, with the labels that each got.

#1401 Refactor code
  .editorconfig
  .github/dependabot.yml
  .github/workflows/push.yml
  CONTRIBUTING.md
  Makefile
  NOTICE
Labels: internal

#1414 restore lost file and fix gitignore that led to that loss
  .coveragerc
  .gitignore
Labels: bug

#1423 Rename mock
  tests/unit/reconcile/connectors/test_secrets.py
Labels: internal

#1402 Labs Yaml Refactor
  labs.yml
  src/databricks/labs/remorph/jvmproxy.py
Labels: internal

#1428 add acceptance
  .github/scripts/setup_mssql_odbc.sh
  .github/workflows/acceptance.yml
  pyproject.toml
  src/databricks/labs/remorph/transpiler/execute.py
  tests/integration/conftest.py
  tests/integration/connections/conftest.py
  tests/integration/connections/test_mssql_connector.py
Labels: stacked PR

#1425 Patch User Agent
  src/databricks/labs/remorph/transpiler/execute.py
  tests/unit/transpiler/test_snow.py
Labels: internal
