Repository databrickslabs/lakebridge, pull requests merged in 2025-05, with the labels that each got.

#1548 Fix test temporary resources
  tests/integration/test_install.py
  tests/unit/helpers/test_file_utils.py
Labels: bug, internal

#1551 Constrain the Databricks SDK to a single version
  pyproject.toml
Labels: dependencies

#1471 Log lsp server stderr
  src/databricks/labs/remorph/transpiler/lsp/lsp_engine.py
  tests/resources/lsp_transpiler/lsp_server.py
  tests/unit/transpiler/test_lsp_err.py
Labels: bug

#1557 Add Pipeline and Step Comment Attributes
  src/databricks/labs/remorph/assessments/profiler_config.py
  tests/integration/assessments/test_pipeline.py
Labels: feature/profiler

#1572 Avoid adding unnecessary semicolons
  src/databricks/labs/remorph/helpers/validation.py
  src/databricks/labs/remorph/transpiler/execute.py
  src/databricks/labs/remorph/transpiler/lsp/lsp_engine.py
  tests/unit/transpiler/test_lsp_engine.py
Labels: bug

#1573 Integration Test with dedicated runner
  .github/workflows/push.yml
Labels: internal

#1571 Wait for transpile capability during LSP initialisation
  src/databricks/labs/remorph/transpiler/lsp/lsp_engine.py
  tests/unit/transpiler/test_lsp_engine.py
Labels: enhancement

#1569 Ensure test LSP server is shut down when tests fail
  tests/unit/transpiler/test_lsp_engine.py
Labels: internal

#1568 Ensure the Remorph CLI provides product information to the pluggable transpilers during initialisation.
  src/databricks/labs/remorph/transpiler/lsp/lsp_engine.py
  tests/resources/lsp_transpiler/lsp_server.py
  tests/unit/transpiler/test_lsp_engine.py
Labels: enhancement

#1574 LSP: include the client's process ID during the initialisation sequence
  src/databricks/labs/remorph/transpiler/lsp/lsp_engine.py
  tests/resources/lsp_transpiler/lsp_server.py
  tests/unit/transpiler/test_lsp_engine.py
Labels: enhancement

#1584 Patch for integration test failure
  tests/integration/assessments/test_pipeline_scheduler.py
Labels: stacked PR

#1580 Reduce logging noise during normal transpiler processing.
  src/databricks/labs/remorph/transpiler/execute.py
Labels: enhancement

#1599 Integration tests: only test against latest Spark 3 release
  .github/scripts/setup_spark_remote.sh
Labels: bug

#1606 Disable (temporarily) integration test: `test_gets_maven_version`
  .github/scripts/setup_spark_remote.sh
  tests/integration/test_install.py
Labels: bug

#1590 Update cryptography requirement (via dependabot)
  pyproject.toml
Labels: dependencies, python

#1611 Update maven installer to not use `search.maven.org`
  src/databricks/labs/remorph/install.py
  tests/integration/install/test_install.py
Labels: bug
