Repository databrickslabs/lakebridge, pull requests merged in 2025-06, with the labels that each got.

#1535 configure synapse credentials
  src/databricks/labs/remorph/assessments/configure_assessment.py
  src/databricks/labs/remorph/cli.py
  tests/integration/conftest.py
  tests/unit/assessment/test_assessment.py
Labels: feature/profiler

#1512 Extend Support for Dependency Management
  src/databricks/labs/remorph/assessments/pipeline.py
  src/databricks/labs/remorph/assessments/profiler_config.py
  tests/integration/assessments/test_pipeline.py
  tests/resources/assessments/db_extract_dep.py
  tests/resources/assessments/pipeline_config.yml
  tests/resources/assessments/pipeline_config_failure_dependency.yml
Labels: stacked PR, feature/profiler

#1634 Change error-reporting during `transpile`
  src/databricks/labs/remorph/transpiler/execute.py
  tests/unit/conftest.py
  tests/unit/transpiler/test_execute.py
Labels: enhancement

#1641 Make transpiler configuration path optional in the workspace transpile configuration
  src/databricks/labs/remorph/cli.py
  src/databricks/labs/remorph/config.py
  src/databricks/labs/remorph/install.py
  tests/unit/test_install.py
Labels: bug

#1647 docs ui enhancements
  docs/remorph/docs/assessment.mdx
  docs/remorph/docs/assessment/analyzer.mdx
  docs/remorph/docs/assessment/profiler.mdx
  docs/remorph/docs/dev/index.mdx
  docs/remorph/docs/installation.mdx
  docs/remorph/docs/motivation.mdx
  docs/remorph/docs/transpile/index.mdx
  docs/remorph/docs/transpile/pluggable_transpilers.mdx
  docs/remorph/docusaurus.config.ts
  docs/remorph/package.json
  docs/remorph/sidebars.ts
  docs/remorph/src/css/custom.css
  docs/remorph/src/css/table.css
  docs/remorph/src/pages/index.tsx
  docs/remorph/src/theme/Footer/index.tsx
  docs/remorph/src/theme/Layout/index.tsx
  docs/remorph/src/theme/Navbar/Content/index.tsx
Labels: documentation

#1651 Explode and store combined output
  src/databricks/labs/remorph/transpiler/execute.py
  src/databricks/labs/remorph/transpiler/lsp/lsp_engine.py
  tests/resources/lsp_transpiler/aggregated_output.mime
  tests/resources/lsp_transpiler/lsp_server.py
  tests/resources/lsp_transpiler/workflow.xml
  tests/unit/conftest.py
  tests/unit/transpiler/test_execute.py
  tests/unit/transpiler/test_lsp_engine.py
Labels: DAIS

#1658 Fix creating default output folder
  src/databricks/labs/remorph/cli.py
Labels: DAIS

#1659 [BUGFIX] Strip prompt question responses in transpile
  src/databricks/labs/remorph/cli.py
Labels: DAIS

#1657 [BUGFIX] Fix bladerunner install from pypi
  src/databricks/labs/remorph/install.py
  tests/integration/install/test_install.py
  tests/integration/install/test_install_and_run.py
  tests/integration/install/test_installer.py
  tests/integration/transpile/test_bladerunner.py
  tests/integration/transpile/test_morpheus.py
Labels: DAIS

#1661 Documentation: Overall flow
  docs/remorph/docs/installation.mdx
  docs/remorph/docs/overview.mdx
  docs/remorph/docusaurus.config.ts
  docs/remorph/sidebars.ts
  docs/remorph/src/pages/index.tsx
Labels: documentation

#1688 Documentation markdown improvements
  docs/lakebridge/docs/assessment/analyzer/export_metadata.mdx
  docs/lakebridge/docs/assessment/analyzer/index.mdx
  docs/lakebridge/docs/overview.mdx
  docs/lakebridge/docs/transpile/index.mdx
Labels: documentation

#1687 Fix issue templates, so issues can be created.
  .github/ISSUE_TEMPLATE/bug.yml
  .github/ISSUE_TEMPLATE/feature.yml
Labels: bug

#1685 Use diagnostics' severity to log their message using the corresponding log level
  src/databricks/labs/lakebridge/cli.py
  tests/unit/test_cli_transpile.py
Labels: enhancement

#1705 Type hints
  src/databricks/labs/lakebridge/config.py
  tests/unit/conftest.py
  tests/unit/test_cli_transpile.py
Labels: tech debt

#1719 Patch Encoding
  src/databricks/labs/lakebridge/cli.py
  src/databricks/labs/lakebridge/transpiler/execute.py
Labels: bug

#1731 Refactor parsing of `java -version` during `install-transpile`
  src/databricks/labs/lakebridge/install.py
  tests/integration/install/test_installer.py
  tests/unit/test_install.py
Labels: tech debt

#1733 Detect (and remove) Unicode BOMs when reading SQL
  pyproject.toml
  src/databricks/labs/lakebridge/helpers/file_utils.py
  src/databricks/labs/lakebridge/helpers/string_utils.py
  src/databricks/labs/lakebridge/intermediate/root_tables.py
  src/databricks/labs/lakebridge/transpiler/execute.py
  src/databricks/labs/lakebridge/transpiler/lsp/lsp_engine.py
  tests/unit/helpers/test_string_utils.py
  tests/unit/transpiler/test_execute.py
  tests/unit/transpiler/test_lsp_engine.py
Labels: enhancement, dependencies
