Repository databrickslabs/lakebridge, pull requests merged in 2025-09, with the labels that each got.

#1967 Pass log-level to LSP server via environment
  src/databricks/labs/lakebridge/transpiler/lsp/lsp_engine.py
  tests/resources/lsp_transpiler/lsp_server.py
  tests/unit/transpiler/test_lsp_engine.py
Labels: feat/cli, tech debt

#1963 CLI entry points, enforce keyword arguments
  src/databricks/labs/lakebridge/cli.py
  tests/unit/test_cli_analyze.py
  tests/unit/test_cli_lineage.py
  tests/unit/test_cli_other.py
Labels: feat/cli, internal

#1949 SQL Validator check for only sql outputs
  src/databricks/labs/lakebridge/helpers/validation.py
  src/databricks/labs/lakebridge/transpiler/execute.py
  tests/integration/transpile/common_utils.py
  tests/integration/transpile/test_bladebridge.py
  tests/integration/transpile/test_morpheus.py
  tests/resources/functional/snowflake/integration/create_ddl.sql
  tests/resources/functional/snowflake/integration/dummy_function.sql
  tests/resources/functional/teradata/integration/create_ddl.sql
  tests/resources/functional/teradata/integration/dummy_function.sql
Labels: sqlvalidator

#1954 Add docs for mssql and synapse reconcile connection
  docs/lakebridge/docs/reconcile/index.mdx
  docs/lakebridge/docs/transpile/pluggable_transpilers/bladebridge_overview.mdx
Labels: documentation

#1985 Add missing transpile source dialect handling
  src/databricks/labs/lakebridge/cli.py
Labels: bug

#1999 Document internal transpiler repository interfaces
  src/databricks/labs/lakebridge/cli.py
  src/databricks/labs/lakebridge/transpiler/lsp/lsp_engine.py
  src/databricks/labs/lakebridge/transpiler/repository.py
  src/databricks/labs/lakebridge/transpiler/transpile_engine.py
Labels: documentation, tech debt, internal

#2013 Support non-interactive installation of transpilers
  labs.yml
  src/databricks/labs/lakebridge/base_install.py
  src/databricks/labs/lakebridge/cli.py
  src/databricks/labs/lakebridge/install.py
  tests/integration/config/test_config.py
  tests/unit/test_cli_other.py
  tests/unit/test_install.py
Labels: enhancement, feat/cli

#2025 README formatting
  README.md
Labels: documentation, internal

#2022 Bump `actions/setup-node` from 4 to 5
  .github/workflows/docs-build.yml
  .github/workflows/docs-release.yml
Labels: dependencies, github_actions, internal

#2052 Work around `DATABRICKS_HOST` normalisation issue during `install` and `uninstall`
  src/databricks/labs/lakebridge/base_install.py
  src/databricks/labs/lakebridge/cli.py
  src/databricks/labs/lakebridge/uninstall.py
Labels: bug, feat/cli

#2060 Ensure consistent ordering when describing the installed transpilers
  src/databricks/labs/lakebridge/transpiler/describe.py
  tests/integration/transpile/test_describe.py
  tests/unit/transpiler/test_describe.py
Labels: bug, internal

#2039 Fix deploy reconcile jobs
  src/databricks/labs/lakebridge/deployment/installation.py
  src/databricks/labs/lakebridge/deployment/job.py
  src/databricks/labs/lakebridge/deployment/recon.py
  src/databricks/labs/lakebridge/reconcile/runner.py
  tests/unit/deployment/test_job.py
  tests/unit/deployment/test_recon.py
Labels: bug, feat/recon, tech debt
