Repository databrickslabs/lakebridge, pull requests merged in 2025-04, with the labels that each got.

#1476 Hot Fix for Dashboard Names
  pyproject.toml
  src/databricks/labs/remorph/deployment/dashboard.py
  src/databricks/labs/remorph/deployment/job.py
  tests/unit/deployment/test_dashboard.py
  tests/unit/test_install.py
Labels: hotfix

#1525 Freshen project YARN dependencies (used to build documentation)
  docs/remorph/yarn.lock
Labels: documentation, dependencies, javascript

#1523 Constrain dependency versions for project
  pyproject.toml
Labels: enhancement, dependencies

#1529 Update transpiler configurations to use a dictionary to specify the environment
  docs/remorph/docs/transpile_guide/pluggable_transpilers.mdx
  src/databricks/labs/remorph/transpiler/lsp/lsp_engine.py
  tests/resources/lsp_transpiler/lsp_config.yml
Labels: documentation, tech debt, python

#1531 Reapply documentation fix from #1486
  docs/remorph/docs/transpile_guide/pluggable_transpilers.mdx
Labels: bug, documentation

#1532 Pluggable transpiler documentation fixes
  docs/remorph/docs/transpile_guide/pluggable_transpilers.mdx
Labels: documentation
