Repository databrickslabs/lakebridge, pull requests merged in 2025-08, with the labels that each got.

#1876 find and replace `remorph` in docs
  docs/lakebridge/docs/reconcile/reconcile_automation.mdx
  docs/lakebridge/docs/reconcile/reconcile_configuration.mdx
Labels: documentation

#1890 Fix semi-broken unit tests on `main` for `installer.py`
  tests/unit/test_install.py
Labels: bug, internal

#1894 Refactor virtualenv setup when installing BB
  src/databricks/labs/lakebridge/install.py
  tests/integration/install/test_install_and_run.py
Labels: feat/cli, tech debt, internal

#1898 Ensure subprocess output is logged upon failure during `install-transpile`
  src/databricks/labs/lakebridge/install.py
Labels: internal

#1893 Fix `install-transpile` if a transpiler backup already exists
  src/databricks/labs/lakebridge/install.py
Labels: bug, feat/cli, tech debt
