Repository databrickslabs/lakebridge, pull requests merged in 2025-10, with the labels that each got.

#2071 Minor pip improvements during `install-transpile`
  src/databricks/labs/lakebridge/transpiler/installers.py
Labels: internal

#2068 Freshen project development dependencies
  .github/workflows/acceptance.yml
  .github/workflows/push.yml
  .github/workflows/release.yml
  pyproject.toml
  src/databricks/labs/lakebridge/deployment/configurator.py
  src/databricks/labs/lakebridge/transpiler/installers.py
  src/databricks/labs/lakebridge/transpiler/sqlglot/parsers/snowflake.py
Labels: dependencies, internal

#1877 [1745] Support snowflake arrays
  src/databricks/labs/lakebridge/reconcile/schema_compare.py
  tests/integration/reconcile/test_schema_compare.py
Labels: bug, feat/recon

#1965 Handle special characters in reconcile aggregate
  src/databricks/labs/lakebridge/reconcile/compare.py
  src/databricks/labs/lakebridge/reconcile/connectors/data_source.py
  src/databricks/labs/lakebridge/reconcile/connectors/oracle.py
  src/databricks/labs/lakebridge/reconcile/connectors/snowflake.py
  src/databricks/labs/lakebridge/reconcile/query_builder/aggregate_query.py
  src/databricks/labs/lakebridge/reconcile/query_builder/base.py
  src/databricks/labs/lakebridge/reconcile/recon_config.py
  src/databricks/labs/lakebridge/reconcile/trigger_recon_aggregate_service.py
  tests/conftest.py
  tests/integration/reconcile/test_aggregates_reconcile.py
  tests/unit/reconcile/query_builder/test_hash_query.py
  tests/unit/reconcile/test_recon_config.py
  tests/unit/reconcile/test_table_service.py
Labels: feat/recon

#2080 bump blueprint
  pyproject.toml
  src/databricks/labs/lakebridge/deployment/configurator.py
Labels: internal

#2083 Add java 25 to the list of versions we verify we can check
  src/databricks/labs/lakebridge/transpiler/installers.py
  tests/unit/transpiler/test_installers.py
Labels: enhancement, internal

#2087 Additional pip-related logging during `install-transpile`
  src/databricks/labs/lakebridge/transpiler/installers.py
Labels: enhancement, internal
